### ISSUE TITLE
[Property Request]: TIRCP Awardee tag

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#101]
### Name of Custom Property

TIRCP Award 2022

### What is the problem that this is solving?

We would like to be able to note which agencies were awarded a TIRCP award. This custom property should be associated with "companies" but we would also like to see it within "deals".

### Object Association

Companies

### When does this property need to be implemented?

ASAP

**Comment by AnthonyRollins** [comment]
@o-ram We can use a dropdown property for `yes` / `no` or do you need more info associated? 

As for seeing this field in the deal, is it just on the sidebar preview of the company profile or do you need it in the table view of the pipelines? I would recommend just adding it to the company preview in the sidebar of the deal.

**Comment by AnthonyRollins** [comment]
Sounds good, I will wait for @esquared415 to chime before I make anything

**Comment by esquared415** [comment]
Hello! 

- I love the idea of a "Grants" property that we could multiple-select as checkboxes (we could come up with a list of grant names to create it ... but we'd need to be able to add other grant names later if we forget one now / learn of another one later). 
- One Q on the Grants concept: How best to also note grant _year_ in addition to grant name / funding type?
- I'd be happy to see this appear in the Company preview sidebar of the Deal. 

Thanks ever so much @AnthonyRollins & @o-ram!

**Comment by AnthonyRollins** [comment]
@esquared415 Send me the multi-select options for a `Grants` property, and I can get that property made and attached to the company profiles. Of course, you can always add to these options, so there is no need to make them perfect.

We are going to have to think through how to add grant year, name and funding type altogether. My initial thought is to add the grant fields to a pipeline and then associate with the companies with those grants. I will continue to look into this to see if there is a better option. That level of data might be best to continue in Airtable ultimately.

**Comment by esquared415** [comment]
@AnthonyRollins I've asked Jess for the grant names and will circle back here when I have that list in hand. Thanks!

**Comment by AnthonyRollins** [comment]
@esquared415 Talked with @o-ram about this: We think we should create a property called `Grants 2022` and then have a multi-select for all the grants awarded to the agency. 

I've added this with some [grant examples](https://app.hubspot.com/contacts/5519226/company/8766327421); let me know if this should work. All grants pulled from [Caltrans DRMT ](https://dot.ca.gov/programs/rail-and-mass-transportation/drmt-grant-modernization) list.

**Comment by thekaveman** [comment]
> We think we should create a property called Grants 2022 and then have a multi-select for all the grants awarded to the agency.

That seems like a good approach to get started. Let me know if you'd like me to join the conversations about:

> We are going to have to think through how to add grant year, name and funding type altogether.

**Comment by AnthonyRollins** [comment]
It would be great to have your input on this, especially as we build out the needs of everyone with Caltrans grants

**Comment by esquared415** [comment]
@AnthonyRollins I'm so glad that you connected with Jess and are thinking about all of this! 

You're right that right now, Payments Pipeline is where knowing an "awarded" grant would be useful ... but eventually, we expect to have other product pipelines (like GTFS / GRaaS hardware, maybe something for CAD/AVL) where knowing customer grant status would also be helpful.

I think it would be a) useful to see "Eligible for" b) alongside Grants 2022 (or moreover Grants 2023, as it's my understanding that many 2022 grant _application_ deadlines have passed).

Maybe what we need is:
**Grant YEAR**
Grant 1 name:   0 Eligible   0 Applied   0 Awarded
Grant 2 name:   0 Eligible   0 Applied   0 Awarded
Grant 3 name:   0 Eligible   0 Applied   0 Awarded

Possible within the property field? Thanks for giving this so much thought, @AnthonyRollins & @thekaveman!

**Comment by esquared415** [comment]
(Oh, and always happy to chat if that's easier. Perhaps with visuals!)

**Comment by AnthonyRollins** [comment]
@esquared415 Thanks for the additional information; very helpful. I need to wrap my brain around how we can do this in Hubspot, update what I have already done in Hubspot, and see if that works.

**Comment by AnthonyRollins** [comment]
One possible solution that I want to get your feedback on, @esquared415, is:

- Update the `Grant 2023` company property that includes a multi-select with the following options:
   - TIRCP: Eligible
   - TIRCP: Applied
   - TIRCP: Awarded
   - Etc. for all Grants 

This would mean that there would be 42 options in the multi-select, which may be too many, and so I was curious about how helpful the `Applied` option is. Do we know that info regularly, and would we be able to update this monthly?

**Comment by esquared415** [comment]
@AnthonyRollins I'm afraid I don't know the answer to the frequency with which we learn Applied info + how/when it would be communicated to us (for updating in Hubspot). Could you ask Jess to check with Maya?

**Comment by AnthonyRollins** [comment]
@esquared415 Sure thing I will add it to our weekly CRM meeting, and thanks for the info!

**Comment by AnthonyRollins** [comment]
@esquared415 Meeting with Jess on Wednesday to discuss the Blackcat data and brainstorm how we might get specific Grants data.

**Comment by AnthonyRollins** [comment]
@esquared415 Meeting with Jess and Maya to discuss future grants that I could get the data on, so I haven't forgotten about this request, just need to find a good source for the data.

**Comment by AnthonyRollins** [comment]
@o-ram @esquared415 Still talking grants over here and curious about how important this property is. Getting data on it to add it to each transit agency is still important or no?

**Comment by esquared415** [comment]
👋 @AnthonyRollins! Just talked to @o-ram about this, and we think it remains a "nice" to have but is not a priority at this time. We would want those fields to contain accurate info and be well maintained—which would require resources allocation. 

Perhaps we revisit as we roll out and staff Client Services?

**Comment by AnthonyRollins** [comment]
OK, we can keep this on hold and return to it after we roll out new staff.

**Comment by AnthonyRollins** [comment]
Related to #208

TIRCP could be added as an option to `Grants Eligibility` property being created. Currently, there is no data to support this new option.

@esquared415 @o-ram I know we talked about putting this on hold, but I do think we can just add this to the #208 property, and when we have data we can add it there, does that work?

**Comment by o-ram** [comment]
@AnthonyRollins The only thing that makes TIRCP complicated is that, technically, all transit agencies are eligible. It's a discretionary grant vs a formula grant. I think LCTOP is the same. So I think it boils down to what we want from this:
1. To know who is eligible? Then, yes, we should just add this to #208 for everybody and call it a day.
2. To know who was awarded? That, in some ways, is actually easier for discretionary grants because there is always a big announcement when the awards come out. And it's usually like once or twice a year at most for the most popular ones. 

If the answer is number 2, then maybe we create a grants property called "Discretionary Grants: Awarded" that we document as the most recent/best knowledge we have?

If this altogether feels like a maintenance nightmare, we could also abandon discretionary grants altogether for now and revisit it another time.

Thoughts @esquared415 ?

**Comment by AnthonyRollins** [comment]
I like option 2, but it is worth a little more discussion. We also might get some TIRCP data for more answers here, but we are still determining what it will be. Would it be helpful to have awarded TIRCP grants attached to agency profiles, or no?

**Comment by AnthonyRollins** [comment]
Reference #281
