### ISSUE TITLE
[Reporting Request]: Customer snapshots

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#183]
Related to [#2681](https://github.com/cal-itp/data-infra/issues/2681)

### What kind of data are you looking for?

Detailed view of a list of activities per customer (transit agency). 

We will need more information from Gillian based on the exact need and cadence in reports.

### When would you like to receive this report?

Monthly

**Comment by o-ram** [comment]
Is this still an outstanding request from Gillian? And if so, any more detail on what exactly she is looking for?

**Comment by AnthonyRollins** [comment]
This is an outstanding request that I still need to ask her about in more depth. I still think this will need integration with the data warehouse, so we can pass data over to Metabase.

**Comment by AnthonyRollins** [comment]
Created and [issue](https://github.com/cal-itp/data-infra/issues/2681) in /data-infra repo:

**Comment by AnthonyRollins** [comment]
Projected for Aug 7th - 21st to begin work on moving data into Hubspot.

**Comment by AnthonyRollins** [comment]
Replaced with Customer Journey pipeline
