### ISSUE TITLE
Hubspot 101 presentation deck

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#188]
## Items to include
- Overview of Contacts, Companies, Deals (pipelines), Marketing and Services (Support Pipeline)
- Weave in demo sessions of specific section overviews (email a contact, mass email, etc.)
- Shouldn't be more than 6-7 slides

**Comment by AnthonyRollins** [comment]
@laneymangan @ProvvidenzaC, any update on the next steps here?

**Comment by ProvvidenzaC** [comment]
Finishing up a content outline today/tomorrow morning to pass off to Laney to inject specifics + additional info. Once we got the once over, we'll convert into slides.

**Comment by laneymangan** [comment]
## Next Steps 
- [ ] @ProvvidenzaC to send outline to @laneymangan 
- [ ] @laneymangan to review and add to outline
- [ ] @AnthonyRollins to review outline
- [ ] @laneymangan to schedule time with @ProvvidenzaC to sync on next steps
- [ ] @laneymangan and @ProvvidenzaC to convert content to slide deck

**Comment by AnthonyRollins** [comment]
@laneymangan reviewed the content outline and made a few comments in the doc; let me know if you need anything else from me.

**Comment by laneymangan** [comment]
- [ ] @ProvvidenzaC working on first draft of slide deck 
- [ ] @laneymangan adds additional info/demos/specifics 
- [ ] @AnthonyRollins reviews deck
- [ ] Team finalizes slide deck and discusses next steps for sharing with broader audience 

(@ProvvidenzaC feel free to add to or edit these steps)

**Comment by AnthonyRollins** [comment]
@laneymangan @ProvvidenzaC Let me know when I should take a look at this.

**Comment by ProvvidenzaC** [comment]
@AnthonyRollins FAQ filled out and generally can overview! Can use above WIP link.

**Comment by AnthonyRollins** [comment]
@ProvvidenzaC @laneymangan I've added some notes to the presentation, let me know if you have any questions

**Comment by laneymangan** [comment]
As discussed, I added in some visuals and reworked the slides to be a bit more digestible. The original text can all be found in the speaker notes. I had to make some format/color changes to support the new visuals. @AnthonyRollins @ProvvidenzaC let me know if you have any feedback/edits/thoughts by tagging me here or via comments in the [deck](https://docs.google.com/presentation/d/1vp3zjclRAAnV_FJ-Yuk2409en24QzSQXSw5-vnN3b_8/edit#slide=id.g22c74e32109_0_26). (CC @o-ram if you'd like to take a look) 

https://docs.google.com/presentation/d/1vp3zjclRAAnV_FJ-Yuk2409en24QzSQXSw5-vnN3b_8/edit#slide=id.g22c74e32109_0_26

**Comment by AnthonyRollins** [comment]
@laneymangan These slides look great. The only thing I would change would be to style and brand these slides using the[ Cal-ITP template](https://docs.google.com/presentation/d/1YjBmMRydfWeorzy-LwLCN2s25472Wz8XxeVuE0bv7n8/edit#slide=id.p1). Let me know if you have any questions.

**Comment by AnthonyRollins** [comment]
Great - I made some changes. Everything looks good.
