### ISSUE TITLE
Develop Customer Success Philosophy

### ISSUE THREAD

**Issue by ProvvidenzaC** [cal-itp/customer-success#216]
- [x] Information gather current outreach procedures and initiatives with @o-ram 
- [ ] Document functional duties for outreach #290 
- [x] #247
- [x] Research best approaches to customer success philosophy in praxis
- [x] Draft customer success philosophy
- [x] Draft review by @o-ram @AnthonyRollins @laneymangan Jess and any other relevant parties
- [x] Edit and provide second draft
- [x] Second draft review 
- [x] Submit draft for Cal-ITP approval

**Comment by o-ram** [comment]
I reviewed the first draft, and I loved it! It hits all the main points and really embodies the spirit of what the CS team is all about. ⭐ ⭐ 

@ProvvidenzaC I responded to the comment that you left, but to summarize here, I love the idea and think we can keep that in mind as the rest of the CS program continues to develop. Maybe it's a near-future next step for the philosophy?

**Comment by AnthonyRollins** [comment]
Closing out this issue as this work will be completed in #290
