### ISSUE TITLE
Process change: Move raising data quality issues into Hubspot

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#238]
The data quality/data services team currently flags data quality issues in Slack, where coordination happens with the CS team to make sure that agencies are reached out to accordingly. We would like to move this process to within Hubspot.

Potential ideas:

1. Use tasks (some experimenting has already gone on with this)
2. Use the internal support pipeline
3. A pipeline (as these issues come and go; might not make sense for this use case)

Deciding on a path will determine the next steps. In order to close this ticket, a clearly defined process should exist for passing data quality issues to the CS team

**Comment by o-ram** [comment]
Current draft: https://docs.google.com/document/d/12Fc4hiaZaz5xG969UcotsLqzgY2tdpnqNS4B_28lpoo/edit#

**Comment by lauriemerrell** [comment]
Draft looks good to me! I basically defer to @evansiroky on the process parameters.

**Comment by o-ram** [comment]
thanks @lauriemerrell and @evansiroky! All comments have been responded to

**Comment by o-ram** [comment]
[Document](https://docs.google.com/document/d/12Fc4hiaZaz5xG969UcotsLqzgY2tdpnqNS4B_28lpoo/edit) is final for now and can be revisited for updates as needed.
