### ISSUE TITLE
[Feature Request]: Create conditional sections based on company type

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#245]
### Feature Request

Our task is to create three distinct custom property categories based on the type of company. By utilizing conditional sections in Hubspot, we can personalize the properties according to the company's type. The current company types include:
1. Transit Agency
2. Vendor
3. Government
4. All other Companies (such as Transit Association or out-of-state Transit agency). 
 
This will ensure that our approach is tailored to the specific needs of each company.

### Is this request related to a problem?

I find the left-side bar on Hubspot Company profiles to be confusing due to the excessive number of properties to sort through, some of which are unrelated to the company being viewed. left-sidebar

### Use Case

When viewing the company type `transit agency`, it is best to display only relevant properties such as grant data, Caltrans district, etc.

### Additional Info

N/a

**Comment by laneymangan** [comment]
Conditional sections have been created for the following company types, which include the properties listed below:
1. Transit agency: account manager, agency acronym, caltrans district, grants eligibility, TAP agency, contract_URL, payment processor, telecom provider. 

- For transit agencies we've also created an additional conditional section called "GTFS Features" 

3. Vendor: vendor type, payment processor

**Comment by AnthonyRollins** [comment]
@laneymangan I believe we can close out of this issue as there are no more conditional sections that we need to create.
