### ISSUE TITLE
Develop Account Manager SOP

### ISSUE THREAD

**Issue by ProvvidenzaC** [cal-itp/customer-success#247]
- [x] Functional workflow documentation
- [x] Update training documents 
- [x] Consolidate all training documents into master SOP

Account Manager Training Guide Draft

**Comment by o-ram** [comment]
@AnthonyRollins @ProvvidenzaC thoughts on closing this issue? I think the 3 tasks are pretty much covered by the training guide doc and all other SOPs/training guides to come out of it are getting their own issues so far.

**Comment by AnthonyRollins** [comment]
@o-ram Works for me.

**Comment by o-ram** [comment]
Issue complete; MVP of [training guide](https://docs.google.com/document/d/18u62_Cz9DV3UqrlAreXqpbirlo0cN4KzWONfDLrTKrE/edit) for account managers produced. Following workflows in need of development will have their own issues.
