### ISSUE TITLE
[Reporting Request]: GTFS task reporting

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/customer-success#248]
### What kind of data are you looking for?

As the transit data quality manager,
I would like to have reports on open/closed tasks related to tracking GTFS data quality,
So that I can show how many things we're working on/how many are open/resolved, etc

I'd also like to be able to have the reports broken out by district.

### When would you like to receive this report?

Monthly

**Comment by evansiroky** [comment]
ok, let's collaborate on this as we move forward. I may end up doing my own reporting given the newly-created transit data quality issue base in Airtable.

**Comment by AnthonyRollins** [comment]
@evansiroky You can review what we have so far in the [dashboard](https://app.hubspot.com/reports-dashboard/5519226/view/10783389). It showcases the current status of all GTFS Quality issues in the [Internal Support Pipeline](https://app.hubspot.com/contacts/5519226/objects/0-5/views/13978724/board), broken down by Caltrans districts. We can add charts to show the month-by-month or week-by-week differences, but there has been little movement with these.

**Comment by evansiroky** [comment]
Interesting, I didn't know that Hubspot could have dashboards. I think we can consider this good for now. Depending on what Gillian asks for in my reporting, I'll let you know if I need more info.

**Comment by AnthonyRollins** [comment]
Yep, we are looking to move some of this data into Metabase so we can have all info in one place too.
