### ISSUE TITLE
May's 017Q monthly report

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#257]
Update slide [deck for May](https://docs.google.com/presentation/d/1MaGSfQy5_K0VH9sUlEeoqDIqnih75-AFTmTDIM4-I3E/edit#slide=id.g13ec71230bf_0_545)

**Comment by AnthonyRollins** [comment]
@o-ram I've finished my sections of the 017Q report. After you've made edits, could assign this issue to @laneymangan to add in her parts/

**Comment by o-ram** [comment]
@laneymangan handing off to you! I believe I'm done. The anecdotes were hard for May, so feel free to replace mine if you have better options!

**Comment by laneymangan** [comment]
@AnthonyRollins passing this back to you. @o-ram and I are done with our portions

**Comment by AnthonyRollins** [comment]
Than you both!

**Comment by AnthonyRollins** [comment]
017Q report was sent in on June 20th
