### ISSUE TITLE
Update Property request issue template

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#260]
Add questions to the Property request template that ask the requestor to tell us which property groups the property should be associated with. This will help the CS team make sure new properties are properly organized.

**Comment by o-ram** [comment]
I will create a training guide as I do this so the team has it for reference (cc @laneymangan)

**Comment by laneymangan** [comment]
Thanks @o-ram! I'll review the training guide once complete so I can help with similar issues in the future

**Comment by o-ram** [comment]
I went to make these edits, but 

1. I couldn't recall the full scope of what we were hoping to add and want to make sure I don't overlook anything
2. I feel like there a few ways we could ask these questions, so hoping to get your input first on the below proposed additions + questions

When the object is a `company`:
**Which company type does this information apply to?**
-Transit Agency
-Vendor

Questions from me: Do we want them to have the option to select both? Or add a third option that says something like all companies (in which case we would just put it in the "about this company" section). None of those?

When the object is a `deal`:
**Which pipeline does this information apply to?**
- Payments
- SchaaS
- Payments Dashboard
- Benefits
- etc....

Questions/notes from me: I know we only have conditional formatting set up for some pipelines right now, but it might come up for the others at some point. Same question as above - should we let people select more than one pipeline? Add an option that says something like all companies (in which case we would just put it in the "about this deal" section). None of those?

@laneymangan @AnthonyRollins LMK your thoughts or if I'm leaving any additions out!

**Comment by AnthonyRollins** [comment]
The questions should go in between: `What object do you want this new property associated with in Hubspot` and `Who is responsible for updating and maintaining this property?`
