### ISSUE TITLE
Rename /crm-helpdesk to /customer-success

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#262]
After reading over Github's [documentation](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository), I don't have access to rename a repo. See screenshot for what I see in the `crm-helpdesk` settings
<img width="1306" alt="Screenshot 2023-06-07 at 5 06 13 PM" src="https://github.com/cal-itp/crm-helpdesk/assets/25047205/1ab4e14f-7664-4403-9f57-99463acd9483">

**Comment by thekaveman** [comment]
Good news, I think I have a solution for redirecting the docs.calitp.org/crm-helpdesk site! Will do this rename and then try that out.
