### ISSUE TITLE
Move CRM Guide edits to online

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#263]
Move recent changes to CRM Guide to docs.calitp.org/customer-success.

**Comment by laneymangan** [comment]
Sections that need updated 
- [ ] [Sales](https://github.com/cal-itp/customer-success/issues/235)
- [ ] [Admin details #1](https://github.com/cal-itp/customer-success/issues/234)
- [ ] [Admin details #2 ](https://github.com/cal-itp/customer-success/issues/231)
- [ ] [Automations](https://github.com/cal-itp/customer-success/issues/233)
- [ ] [Marketing](https://github.com/cal-itp/customer-success/issues/230)
