### ISSUE TITLE
Reset to Account Default feature

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/customer-success#265]
- [x]  submit Hubspot issue to see if there is a work around
- [x] create training guide
- [x] confirm all updates have been made in hubspot ("about us" property order, conditional sections)
- [x] alert broader team to reset their accounts

**Comment by AnthonyRollins** [comment]
@laneymangan I am unsure if we have more changes, but I think we should alert everyone to make these changes. Do we have a Scribe for this? I do remember seeing something for this.

**Comment by laneymangan** [comment]
here ya go! [Scribe](https://docs.google.com/document/d/1pt9o9gAeYSVfRgQKiW3fXyJvoGrGmEPC57PdKgVgkxw/edit)

**Comment by AnthonyRollins** [comment]
I think we are ready to send this out

**Comment by AnthonyRollins** [comment]
@laneymangan this training is for Contacts,  I thought the priority was to update account settings for Companies

**Comment by laneymangan** [comment]
@AnthonyRollins I didn't think it mattered which object I used since the process is the same for all objects, so I just chose a random object and made notes throughout the doc to try to explain that the process is the same regardless of the object (screenshots below). I was thinking that this training guide would live on (so I kept it general), and thought we'd share this out with a slack message explaining which objects needed to be updated this go-round. I believe we made updates to all objects, but the changes for contacts were pretty minimal (just the order of properties and added district staff property, unless I'm forgetting any) so I can easily update the training guide to use companies as the example if you think that's better! 

<img width="634" alt="image" src="https://github.com/cal-itp/customer-success/assets/107429473/f8ac4c77-c9b8-40a9-a386-56983969fcf4">
<img width="643" alt="image" src="https://github.com/cal-itp/customer-success/assets/107429473/e49b8b49-8256-4a87-8bb2-ff097f5ecfb1">

**Comment by AnthonyRollins** [comment]
@laneymangan Oh, okay, this makes sense.

**Comment by laneymangan** [comment]
DRAFT MESSAGE:

Attention all Hubspot users! In an effort to make Hubspot records as useful as possible, we occasionally make property updates to better support the needs of the team. We have made quite a few changes to all Objects (Objects = Companies, Contacts, Tickets + Deals) that will require all users to update their account to the "account defaults". To do so, please see the Training Guide here [link]. You will have to repeat this process for all 4 objects. I promise it shouldn't take more than a few minutes! But please don't hesitate to reach out if you have any questions or need 1-1 support. See more in the threads for the types of updates you can expect. 
Thread:
Once you update your account, you will see changes made to the record view of all objects. For example, the properties that appear within Company records will be tailored to the Company Type. For the Transit agency example below, you will see additional sections, such as "Transit Agency Details", which includes additional information that only applies to Transit Agencies, such as Account Manager. 
<img width="352" alt="image" src="https://github.com/cal-itp/customer-success/assets/107429473/d798228f-80e8-44ed-9c2d-aeff0d3e62c0">

You will see a similar change when viewing Deals. The properties that appear within a Deal will now be tailored to the specific pipeline. 
<img width="345" alt="image" src="https://github.com/cal-itp/customer-success/assets/107429473/cb9d9031-fcab-49b4-829c-a4a5248024b2">

Please let me or @ anthony know if you have any questions at all!

**Comment by laneymangan** [comment]
@AnthonyRollins can you take a look at this draft message? I kinda struggled to find a concise yet thorough way to explain everything...

**Comment by AnthonyRollins** [comment]
@laneymangan This looks good to me - you can send it off. Let's make sure to post in #customer-success and if you need me to shorten, I can but I think attaching the Scribe and threading the post works for me.

**Comment by laneymangan** [comment]
message shared in slack
