### ISSUE TITLE
Develop Internal Support Pipeline SOP

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/customer-success#268]
[SOP WIP](https://docs.google.com/document/d/1SpxlMizdgIpLHDx9Qi8K4SjQpqOYzcwYmPLTMxBZEmQ/edit#heading=h.bsbtr8tx4dqq)

- [x] convert to new SOP format

**Comment by AnthonyRollins** [comment]
Created 7/17

**Comment by laneymangan** [comment]
@o-ram would you mind [looking this over](https://docs.google.com/document/d/1SpxlMizdgIpLHDx9Qi8K4SjQpqOYzcwYmPLTMxBZEmQ/edit#heading=h.2xzb0r6ihpk1) when you get a chance? Any feedback / edits are welcome but would especially like a second pair of eyes on the details surrounding the GTFS Data Quality tickets to make sure I'm getting that right. 

Feel free to reassign me if there are any edits I need to make or pass along to Kathryn to review. Thanks!!

**Comment by o-ram** [comment]
@laneymangan I made a few minor suggestions, but other than that, this looks great! If you're good with my edits, I think you can pass it along to Kathryn. Thanks!!

**Comment by laneymangan** [comment]
Thanks, @o-ram! Passing this to @kathrynmsullivan --would you mind taking a look at our new [Internal Support Pipeline SOP](https://docs.google.com/document/d/1SpxlMizdgIpLHDx9Qi8K4SjQpqOYzcwYmPLTMxBZEmQ/edit)? It should help explain the purpose of / how we manage the [internal support pipeline](https://app.hubspot.com/contacts/5519226/objects/0-5/views/all/board). We're also hoping we could use your fresh eyes to flag any holes, unclear language etc. Let us know if you have any questions!

**Comment by kathrynmsullivan** [comment]
@laneymangan - for sure! I'll make comments directly on the doc if that's ok?

**Comment by laneymangan** [comment]
@kathrynmsullivan that would be great! thanks!

**Comment by kathrynmsullivan** [comment]
@laneymangan - Read through the rest of the doc, it makes sense to me!
