### ISSUE TITLE
Update README.md content

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#283]
[README.md file ](https://github.com/cal-itp/customer-success/blob/main/README.md) hasn't been updated since we first created the repo and added in the issue templates over 6 months ago. Since then, there have been quite a few updates to Customer Success, as this repo doesn't only include CRM changes/updates. 

This issue should be updated after creating a new issue template #282 and include more information on Customer Success and the CRM guide. Items to include in this update:
- [x] Cohort issue template to the table
- [x] Account manager SOP
- [x] CRM Guide
- [x] CS philosophy
- [x] Outreach campaign template

**Comment by laneymangan** [comment]
@kathrynmsullivan I'm working on edits for the READ.ME [in this doc](https://docs.google.com/document/d/1IPkgaf0p6EB-Ja-pUWXqb5-ILlpVyP8qbkm3bV4D9UI/edit) if you'd like to follow along and/or provide input!

**Comment by kathrynmsullivan** [comment]
Cool beans, will do!

**Comment by laneymangan** [comment]
Thanks for your input on the [updated README](https://docs.google.com/document/d/1IPkgaf0p6EB-Ja-pUWXqb5-ILlpVyP8qbkm3bV4D9UI/edit#heading=h.9sdfqh5gr8rc) @AnthonyRollins! @o-ram would you like to review? Feel free to make edits within the doc. Once it's finalized, I'm happy to update the markdown file and close out this issue.

**Comment by AnthonyRollins** [comment]
@laneymangan Did you need me to post on our docs.calitp.org site, or are you going to handle that?

**Comment by laneymangan** [comment]
@AnthonyRollins I'll give it a shot!

**Comment by o-ram** [comment]
@laneymangan thanks for the tag, I think this looks good! I responded to the comment you still had open with one suggestion, but it's minor.

**Comment by AnthonyRollins** [comment]
@laneymangan Let me know if you want me to open the PR or if you are going to handle that.

**Comment by laneymangan** [comment]
@AnthonyRollins I went ahead and opened the PR and requested your review. Let me know if there are any issues. Thanks!
