### ISSUE TITLE
[Cohort Request]: City of Pasadena

### ISSUE THREAD

**Issue by vykster** [cal-itp/customer-success#284]
### What is the name of the agency?

City of Pasadena or Pasadena Transit

### Why do you believe they should be added?

They are about to issue an RFI on transportation technology. 

### Who currently communicates with this agency?

Vyki

### Do you know if there will be increased communication with this agency in the future?

yes

### What contacts from this agency should we be in touch with?

Antonio Watson

### Do you have any additional comments?

Vyki met at a SoCal procurement fair on 6/22/2023. Met two staffers -- gave them Cal-ITP stickers. They indicated their Dept of transportation would be issuing a RFI in the next 2-3 weeks on transit tech and encouraged us to look for it and respond. 

It seems additionally there may be duplicated for Pasadena in Hubspot https://app.hubspot.com/contacts/5519226/objects/0-2/views/all/list?redirectFrom=crm-records-ui&query=pasadena

Antonio was a speaker at the event his title is listed as "Project Manager City of Pasadena Department of Finance and Purchasing Division"

**Comment by laneymangan** [comment]
Thanks @vykster, your request has been received and the team will evaluate based on capacity. Also, the Pasadena hubspot dup has been addressed, thanks for flagging that!

**Comment by AnthonyRollins** [comment]
@o-ram, I'm going to close out this issue as this will be absorbed by the new tier system. Let me know if this should stay open for any reason?

**Comment by o-ram** [comment]
Nope, all good with this being closed, thanks for doing that!
