### ISSUE TITLE
June monthly metrics report

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#285]
Link to [presentation](https://docs.google.com/presentation/d/1q7eV57zx2VQ42BCjCVZyiqb69vzXMsFaDu6_OzI0m3g/edit#slide=id.g13ec71230bf_0_270)

**Action items**
- Incorporate more metrics about our OKRs
- Update slides with June metrics

**Comment by o-ram** [comment]
@AnthonyRollins I'm done with this. Passing to @laneymangan to look over! General note: the anecdotes slide continues to be a time-consuming struggle most months so it might be good to brainstorm what to do with that slide soon.

**Comment by laneymangan** [comment]
@AnthonyRollins done! updated CRM maintenance slide. Passing back to you

**Comment by AnthonyRollins** [comment]
Sent via Slack on July 19th.
