### ISSUE TITLE
Philosophy in practice

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#290]
This issue aims to add to the work done in #216. After adopting customer success philosophies with Cal-ITP, we need to showcase our philosophy in examples throughout the workstreams of Cal-ITP.

- [x] Retrieve workflow examples from @o-ram 
- [x] Philosphy in Practice WIP [here](https://docs.google.com/document/d/1iRvUlU4NeIVfE7yYXX2cP9yzfeYfiUeXL1YKXr59mjM/edit?usp=sharing)
- [ ] Customer Success team review document.

**Comment by o-ram** [comment]
@AnthonyRollins I don't think so - I also identified the MOS doc as a good one to reference. We don't have a lot of "done" workflows, but we hopefully have enough to provide a picture. I have a doc I'm about to pass to Enza, and Kathryn/Enza/I are meeting tomorrow to chat through workflow examples and next steps.

**Comment by o-ram** [comment]
@ProvvidenzaC [here is a doc](https://docs.google.com/document/d/1yyYlEjDr-8JWQQHbMVX5VUy8aHkZztx5zJyErW3WHdU/edit) for you related to workflow examples! We can chat through this tomorrow and where to go next. (cc @kathrynmsullivan and @AnthonyRollins)

**Comment by AnthonyRollins** [comment]
@o-ram These are great, and something when finalized or at least in draft form to share with everyone.

**Comment by kathrynmsullivan** [comment]
Adding the section "How does the Customer Success Philosophy show up here?" to each section. My goal is to be done with that & the table by Monday!

**Comment by ProvvidenzaC** [comment]
Hi @kathrynmsullivan @AnthonyRollins and @o-ram ! Added the Philosophy in practice to the original issue and here[https://docs.google.com/document/d/1iRvUlU4NeIVfE7yYXX2cP9yzfeYfiUeXL1YKXr59mjM/edit?usp=sharing](url) for folks to review and comment.

**Comment by kathrynmsullivan** [comment]
@AnthonyRollins - I completed a review of the document, adding the table with a brief introduction.

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan I reviewed and made a few edits. This is ready to finalize. Let's add the Cal-ITP logo to the doc, and we can use the approval feature in Google Docs to finalize it.

**Comment by kathrynmsullivan** [comment]
Great! @AnthonyRollins -  I added you as the approver, would you like someone else to be the approver?

**Comment by o-ram** [comment]
Happy to review this if you'd like me to, just LMK!

**Comment by kathrynmsullivan** [comment]
@o-ram - sure! Anthony did a final look. I think after your review we can finalize it!

**Comment by o-ram** [comment]
@kathrynmsullivan I left some very minor suggestions to match some wording used in other docs but overall this looks great! I admittedly don't know the ins/outs of the approval feature so I just added my suggestions and did not click "approve" or "reject" yet. Hopefully, the suggestions look fine to you, and if so, I'll click "approve" or do whatever it is you tell me to in order to give it that final sign off.

**Comment by AnthonyRollins** [comment]
@o-ram I think you can approve it.

**Comment by o-ram** [comment]
@AnthonyRollins I already did approve it on the 17th. LMK if it didn't register and I'll do it again.

**Comment by AnthonyRollins** [comment]
Looks good to me. We can close this out.
