### ISSUE TITLE
Quarterly check-in SOP

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#294]
Draft Account Manager process for quarterly check-ins

**Comment by o-ram** [comment]
@laneymangan draft is [here](https://docs.google.com/document/d/156p1a-P7fwU8yY_kWzaR8nyw0LOHXADH6D4g3HCnKxM/edit)! Nowhere near where I wanted it to be before handing it off, but still think it's in a decent state to start getting your and Kathryn's feedback and thoughts. Some parts still need a lot of work though :)

**Comment by o-ram** [comment]
To be revisited in 2024.

**Comment by laneymangan** [comment]
I've added myself as an assignee to keep this on my radar

**Comment by o-ram** [comment]
[This SOP](https://docs.google.com/document/d/156p1a-P7fwU8yY_kWzaR8nyw0LOHXADH6D4g3HCnKxM/edit) has been revised and reviewed by both me and Laney. It is now considered final, so we are closing out this issue.
