### ISSUE TITLE
Update Customer Success Github Project

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#295]
Post-team discussion, the following updates need to be made to our project.

Revise labels/status:
- [x] Add “Review”
- [x] Remove “Stretch” + point system
- [x] Add KR field
- [x] Remove priority field

**Comment by AnthonyRollins** [comment]
Update the Customer SUccess project; let me know if I got everything else on your checklist, @o-ram

**Comment by o-ram** [comment]
Looks good! I added the KR field to our [project board view](https://github.com/orgs/cal-itp/projects/23/views/8), so we can start to incorporate that. Thanks for finishing this up!
