### ISSUE TITLE
Update Account Manager one-pager

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#296]
Revise "one-pager" to better highlight CS guidelines/expectations for how other teams should interact with account managers and keep them informed

**Comment by AnthonyRollins** [comment]
- Should be cc'ing the account manager
- AM responsible for keeping Hubspot profiles updated

Intake process
- Tell people how to interact with AMs -> Github
- Need help with reaching out to agencies - talk with Customer Success
- We help all agencies, not just cohort
- Refresh the definition of the cohort
- **high touch** (cohort), **medium touch** one-off campaign interaction (trinity - connectivity campaigns), **low touch** Expired or broken GTFS feed, reactive support communication (`Hello@`)

**Comment by AnthonyRollins** [comment]
@o-ram add to agenda with Jess.

**Comment by o-ram** [comment]
Was not able to get to this before the end of the year. Marking the issue as "paused" and will revisit in Jan '24 in light of documentation/announcements that will be needed related to the tiers system, as well as other priorities.

**Comment by AnthonyRollins** [comment]
@o-ram Let's shoot for end of February to finalize these updates, a part of a larger push for updates before the new account manager joins.

**Comment by o-ram** [comment]
v2 draft complete and waiting on review from Laney. This new draft introduces the tiers and freshens up the other sections.

**Comment by o-ram** [comment]
This has been reviewed and finalized! [Doc](https://docs.google.com/document/d/1LBxKkuugRKPFa5e3BoCQM4sIO0miJwLpxSyA8kRd14s/edit#heading=h.31pkpwiacyux) has been marked as "ready" within the doc catalog.
