### ISSUE TITLE
Account Manager introductions

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#298]
- [x] Draft Email copy
- [x] Have email copy reviewed
- [x] break up agencies by who needs an intro and who doesn't
- [x] ~Send emails to all on list~ Create HubSpot tasks for needed introductions, since they will roll out. Creating the tasks will satisfy completion of this portion of the issue.
- [x] Add steps on "how to use this template"

Once complete, fold mention/announcement of this into some sort of wider Cal-ITP communication - will be folded into the weekly slack message posted on Friday. We determined it does not need a special announcement of its own.

**Comment by o-ram** [comment]
@laneymangan here's the [email copy](https://docs.google.com/document/d/1y0ZEdlPGBnjexWXEls94Pidkbqbt5Y4Kp5Duun3OLAw/edit) I've been mentioning. Thoughts/ edits welcome! You can ignore the top where I'm doing some agency grouping, since not all agencies will need this. I'll also give this to Kathryn to take a look at after you :)

**Comment by o-ram** [comment]
Adding Kathryn as an assignee since she is reviewing along with us as we edit, make plans for specific agencies, etc 🙂

**Comment by kathrynmsullivan** [comment]
It looks good! I made one comment on the doc. Do I need to assign it back to you @o-ram?

**Comment by kathrynmsullivan** [comment]
@o-ram - I like the instructions! Let me know when you want me to review :)

**Comment by o-ram** [comment]
Thank you! @kathrynmsullivan and @laneymangan ready for you both to take one more look over this and then I think it's ready for us to use as we continue to roll out the official introductions to individual agencies.

**Comment by laneymangan** [comment]
I think it looks great! No edits. Let me know if I can help with creating Hubspot tasks or anything else here @o-ram

**Comment by o-ram** [comment]
@laneymangan thanks for the offer! If you have time, would love for your help with creating Hubspot tasks. Definitely not an urgent thing though, so no worries if you don't have time. We've just been crossing agencies off at the bottom of the doc who either have received an intro or don't need one, but the ones left should likely be moved into Hubspot.

**Comment by o-ram** [comment]
Tasks have been created and will continue to be completed and tracked there
