### ISSUE TITLE
Develop next phase of Hubspot 101 training

### ISSUE THREAD

**Issue by ProvvidenzaC** [cal-itp/customer-success#299]
This issue focuses on creating a bridge between developed training materials and training acquisition by team members beyond the immediate Customer Success team.

- [ ] Create learning strategy for multiple ways of knowing (facilitated presentation, recorded webinar, additional training tools, etc)
- [ ] Consider select user lists for learning
- [ ] Name cohort goals 
- [ ] TBD

**Comment by AnthonyRollins** [comment]
@ProvvidenzaC we have the new feedback form to starting learning what agencies need, and still need to send it to a few first agencies, and then we can start on what agencies need.

**Comment by AnthonyRollins** [comment]
@ProvvidenzaC Create  a new github issue on the results of the feedback survey.
