### ISSUE TITLE
Email Template SOP

### ISSUE THREAD

**Issue by kathrynmsullivan** [cal-itp/customer-success#300]
Streamline communications with reviewed email templates.  

- [ ] Brainstorm Email Templates: What are the various comms we can templatize? 
- [ ] First Draft
- [ ] Peer Review
- [ ] Final Draft

[Document in Cal-ITP -> @customersuccessworkspace -> process documentation ](https://docs.google.com/document/d/1oWJ8HFNwskR5DGmsRL8yY3fNAjrNNU_RsAvatAFKbrI/edit)

**Comment by o-ram** [comment]
@kathrynmsullivan Here are some templates to be aware of:

- Data Quality outreach (drafts we were working on that have been paused for a bit): https://docs.google.com/document/d/11pBgS-Hx5EQ6vbXagR52-ClK3jNYq9yJLQNp5HXzt2I/edit#heading=h.3nvwwm1u3qtn
- Templates for the connectivity campaign: https://docs.google.com/document/d/1AAaOmB8xpdG-hKFaqTQTioeo7HbrblN600Gq2T7KDXQ/edit#heading=h.5klmhvrfw9g9
- List of templates we have saved in Hubspot: https://app.hubspot.com/templates/5519226/ (a lot of these are old or testing but can still provide some good context)

If I think of any others, I'll add them here!

**Comment by kathrynmsullivan** [comment]
Thank you for these templates!

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan we should look to complete this before the new account manager. With all the pending items, let's find some time in March to start on this.
