### ISSUE TITLE
Add maintenance responsibility section to Pipeline request form 

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/customer-success#301]
As we have been developing the details for account manager profile maintenance, we have recognized the need for clear expectations from the get-go around maintaining records and adding notes for new pipelines. We would like to add a question within the pipeline request form around who will be responsible for what, or a note in the request that ensures the requestor understands we will have to collaborate to establish responsibilities.

**Comment by AnthonyRollins** [comment]
@laneymangan I can take on creating this new pipeline question. Did you have any copy in the works for this, if not, I can start fresh on this.

**Comment by AnthonyRollins** [comment]
That sounds great - I'll make sure to assign this to me.
