### ISSUE TITLE
Conference Research & Preparation

### ISSUE THREAD

**Issue by kathrynmsullivan** [cal-itp/customer-success#304]
- [x] #305
- [x] Travel Expenses 
- [x] Accommodations
- [x] #314
- [x] Technology & Equipment 
- [x] #313
- [x] #315
- [x] #316
- [ ] #336
- [x] #338 
- [ ] #339
- [x] #344

**Comment by kathrynmsullivan** [comment]
@o-ram - did you mention that you knew someone about conference materials (banner, promotional materials) or am I miss-remembering that?

**Comment by o-ram** [comment]
hm, I don't know anyone specifically for conference materials, but this could've been related to the design firm Cal-ITP uses for branding, logos, graphics, etc, Place & Page. I recall us briefly discussing that if we need help with designing materials or a banner, we could see if they could help us out. Does that ring a bell?

**Comment by AnthonyRollins** [comment]
Proposal submitted
