### ISSUE TITLE
Conference Registration (Tabling)

### ISSUE THREAD

**Issue by kathrynmsullivan** [cal-itp/customer-success#305]
## To-Do
- [x] Reach out to conferences for tabling pricing

[APTA Tech](https://www.aptaexpo.com/apta2023/Public/Enter.aspx) 
[California Transit Association Fall Conference & Expo](https://caltransit.org/Events/Annual-Conferences/Fall-Conference-Expo)
[CALACT 2023 Fall Conference and Expo](https://calact.org/spring-conference-and-expo-2023/)

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan, Could we reach out this week to find pricing on event tabling?

**Comment by kathrynmsullivan** [comment]
Yeah! I have time blocked out tomorrow for conference research. My plan of action is to prioritize the three conferences you shared, to check out each website and see if that information is listed, and if not find a number to call or email. Does that seem like a good game plan?

**Comment by kathrynmsullivan** [comment]
@AnthonyRollins - [I wrote my initial findings on this google doc. ](https://docs.google.com/document/d/1JNYVRv-zP26wMo-CMRtTWErZkh8cVeGF0_2nfvEyGsw/edit) I have emailed folks to see if there were other options besides booths.

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan This is great. Let's move the cost info into a spreadsheet to assemble a total budget for all the hard costs. We can also add in hotel and airfare too that spreadsheet so we can the totals for each conference.

**Comment by kathrynmsullivan** [comment]
Cool, here's the [excel](https://docs.google.com/spreadsheets/d/18KZn5bPuaA5DA7oWmPkJrR0NiDBPAGu28tDSst2lxZ8/edit?usp=sharing) I'll work off.

**Comment by kathrynmsullivan** [comment]
I think this is complete...? @AnthonyRollins

**Comment by AnthonyRollins** [comment]
Yep, I think this is a good to close.
