### ISSUE TITLE
Brainstorm a list of snippet use cases

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#306]
We currently have snippets for Deal note updates and Company note updates. There is the potential to have many more snippets for various use cases, should they exist. We should brainstorm and produce a list of snippets that we would like to create.

Important to keep in mind the training guide for creating a note, which currently only covers creating a general note (with no snippet) and creating a note using the Deal snippet. As we continue to add on snippets, we should make sure to keep this training guide up-to-date.

**Comment by AnthonyRollins** [comment]
@o-ram would this be good to have for the new hire? If so, we can add this to the schedule for March to finalize.

**Comment by o-ram** [comment]
Yes, we think this could be helpful, we would just need to do some brainstorming. Slotted it for March cc @laneymangan
