### ISSUE TITLE
Track contracts

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#307]
As Cal-ITP seeks to continue collecting contracts, questions continue to arise over the role of the CS team in this effort along with contract storage. We know the following 3 items are useful for account managers: Contract vendor, products/services the contract is for, and expiration date. Contracts are currently stored in Airtable (and linked to from Hubspot) but nobody is in charge of maintaining that info or monitoring it. Questions have arisen regarding the feasibility of including greater contract info in Hubspot.

This issue serves as a placeholder for figuring out where to go next and will evolve with more specific "completion" criteria.

**Comment by o-ram** [comment]
As a starting place, we will meet with Scott, who is scoping a plan for the contract work requested by stakeholders.

**Comment by AnthonyRollins** [comment]
@o-ram Have we heard anything about this? I would like to see if we can get this implemented in Hubspot at some point.

**Comment by laneymangan** [comment]
Meeting scheduled for 12/6. Contracts has been added to agenda

**Comment by laneymangan** [comment]
Discussed with Scott, [notes can be found here](https://docs.google.com/document/d/1gDX9BAcnIhbAUN3Rbdfs9cWViXFl0tIbNLZXcGN3tm0/edit). 

To note: 

- Contracts currently on xentrans drive 

- No current plan for long term storage, open to keeping there wherever everyone thinks would be beneficial 

- CS should let Scott know what we need or think would be helpful

- Contracts might be another custom object for Hubspot, along with Grants, and Vendors

**Comment by AnthonyRollins** [comment]
@laneymangan unless something changes, I think we can plan to use this data for the new custom object, contracts. We will likelly work on this in Q2, so we can find sometime in May or June. I've added a `start date` and `target date`.
