### ISSUE TITLE
017Q July Monthly Report

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#310]
[July Report](https://docs.google.com/presentation/d/1uxwRaeXG3ArGwc6HNXEzxJl-148wqNWeyCfDDKhMYU4/edit#slide=id.g13ec71230bf_0_270)

## To-Do
- [ ] Update metrics for July
- [x] Update completed and what's next sections

**Comment by AnthonyRollins** [comment]
@o-ram Passing this over to you to update a few sections.

**Comment by o-ram** [comment]
@laneymangan over to you! I think all that's needed is to update the maintenance metrics and anything else you usually take a look at.
