### ISSUE TITLE
Conference Materials (Banners, promotional materials)

### ISSUE THREAD

**Issue by kathrynmsullivan** [cal-itp/customer-success#314]
Promotional materials for conferences. 
- [x] Tablecloth
- [x] Cal-ITP Banner 
- [x] Acrylic Sign [Holders](https://www.amazon.com/s?k=plastic+display&crid=33HN56YX78LED&sprefix=plastic+display+%2Caps%2C154&ref=nb_sb_noss_2)
- [x] Stickers
- [x] Reach out to Jeremy about using Colleen (Olivia will ask Erika E. about using Colleen)
- [x] #345
- [x] Order [One-Pagers](https://www.vistaprint.com/marketing-materials/flyers)
- [x] Confirm with Lexi that Cal-ITP is in the Accelevents app(my account is blank)

**Comment by kathrynmsullivan** [comment]
@o-ram - when you email erika about Colleen can you cc me so I can support while you're out? Thank you!

**Comment by laneymangan** [comment]
**[Retractable Banner from VistaPrint](https://www.vistaprint.com/signs-posters/retractable-banners)**

Size: 33" x 81"
<img width="893" alt="image" src="https://github.com/cal-itp/customer-success/assets/107429473/fe47d655-1de7-4d9d-abc8-1aca297d6026">

<img width="225" alt="image" src="https://github.com/cal-itp/customer-success/assets/107429473/b8c87b77-13cd-4d93-bcfa-a42942818db1">

<img width="451" alt="image" src="https://github.com/cal-itp/customer-success/assets/107429473/a1a3459b-8645-4504-a568-89d0e0db2067">

<img width="1047" alt="image" src="https://github.com/cal-itp/customer-success/assets/107429473/bd45cca6-99b6-4c12-876d-277605c04b8d">

**Comment by laneymangan** [comment]
@AnthonyRollins @kathrynmsullivan do we know the size of the table for the conferences? Vista print has 4, 6, and 8 foot table cloth options

**Comment by kathrynmsullivan** [comment]
Acrylic Sign Holders - 6 pack and 12 packs on [Amazon](https://www.amazon.com/s?k=plastic+display&crid=33HN56YX78LED&sprefix=plastic+display+%2Caps%2C154&ref=nb_sb_noss_2).

**Comment by kathrynmsullivan** [comment]
Maybe package 4?? [Screenshot 2023-08-31 at 12 19 18 PM](https://github.com/cal-itp/customer-success/assets/139281146/8f0c49bd-1567-44bc-9a3a-b7862b287943)

https://www.tricord.net/wp-content/uploads/2023/08/CTA-2023-Exhibitor-Kit.pdf

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan Interesting; I didn't realize we had to rent furniture at the events. Generally, I think package 4 makes the most sense for us.

**Comment by kathrynmsullivan** [comment]
Notes from Colleen Meeting (8/31/23)
- Suggesting a tablecloth and pull-up banners
- Pull-up banners, vertical banners, are easier to use
- Colleen needs:
- What kind of messaging do we want on our banners? Our mission? Services? 
- Turnaround is fairly quick 
- Vista print is fine
- black sheep press is a local LA vendor and deliveries to the compiler building often

**Comment by kathrynmsullivan** [comment]
@AnthonyRollins - I didn't realize that either and agree option $4 is good for us. For CALACT, in your booth confirmation email, does it say what is provided in the booth?

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan In your email, it looks like there is a rental discount deadline, so I feel like there might be stuff we need to rent. I didn't receive any details on renting any equipment.

**Comment by kathrynmsullivan** [comment]
One Pagers: [Vistaprint](https://www.vistaprint.com/marketing-materials/flyers) can create 8.5 x 11 flyers, vertical, 3 options for paper stock (recycled, glossy or matte). 
Recycled: 50 = $51.99, 100 ($.80 / unit = $79.19) or 250 ($.48 / unit = 119.19)
Glossy or Matte: 50 = $35.19, 100 (.54 / unit = $53.59) or 250 ($.33 / unit = $80.79)

**Comment by AnthonyRollins** [comment]
I based the budget on creating 100 copies for each one-pager, so I estimated we would bring 4 one-pagers.

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan Cal-ITP stickers arrived today.
