### ISSUE TITLE
Content Promotion

### ISSUE THREAD

**Issue by kathrynmsullivan** [cal-itp/customer-success#316]
To achieve our goal of connecting with as many travel agencies as possible, we need to make sure they know we are attending both conferences. 

- [x] AM's Reach out to the cohort that CS is attending 
- [ ] Add to the next [newsletter](https://app.smartsheet.com/b/form/039d081870e640a9809971448b1be553)
- [x] Send in #customer-success that we will be attending conferences.

**Comment by kathrynmsullivan** [comment]
@AnthonyRollins  -[ I did this on Friday ]...It's a draft of the Account Manager Email to agencies. 
(https://docs.google.com/document/d/19QdKM0FEt1UMgj7GU1czMNcmvmnlwVstH6wq-eR72JI/edit)

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan Updated the doc with the Slack post, @o-ram when you get the chance, can you take a look at the email to the agencies.

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan Posted to customer-success and general Slack channel. 

I can fill out the form to include us in an upcoming newsletter, but I will leave it to @o-ram and @kathrynmsullivan on the note to our agencies.

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan Did we send out emails to our agencies letting them know we will be at CALACT and CTA

**Comment by kathrynmsullivan** [comment]
@AnthonyRollins - I will check w/ @o-ram & @laneymangan as see if we can check this off!

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan Can we close out this issue?
