### ISSUE TITLE
Revise monthly metrics report

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#317]
Make the following edits/additions to the monthly report:

**Comment by o-ram** [comment]
@AnthonyRollins made this placeholder issue since monthly reporting was on my mind 😄 Figured we can use this issue to track the updates we want to make going forward.

**Comment by AnthonyRollins** [comment]
@o-ram This makes a lot of sense as we will have a recurring issue pop up at the beginning of September for us to implement the new ideas we have here. 

@vykster We've talked a lot about improvements we can make to the 017Q report - feel free to add new ideas here.

**Comment by AnthonyRollins** [comment]
I've added in some new changes for the August report - let me know if you have any others @o-ram or if we should close out this issue.
