### ISSUE TITLE
Develop outreach strategy for ODS Campaign

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#319]
_placeholder for tracking work coming out of the past & upcoming conversations with Scott re. how CS can help with ODS_

**Comment by o-ram** [comment]
@laneymangan opened this one and #318 as placeholders for now!

**Comment by laneymangan** [comment]
Meeting scheduled for 12/6

**Comment by laneymangan** [comment]
Meeting notes can be found [here](https://docs.google.com/document/d/1gDX9BAcnIhbAUN3Rbdfs9cWViXFl0tIbNLZXcGN3tm0/edit). Team will check back in with Scott in the new year. Outreach is expected to begin mid january-february following release of version 2.0.

**Comment by AnthonyRollins** [comment]
Do you think we should combine this with #346? This issue appears to be similar. We should plan for this campaign to be taken off in February, but I believe @kathrynmsullivan will be reaching out to confirm dates.

**Comment by laneymangan** [comment]
Yeah I think this can be merged with #346

**Comment by laneymangan** [comment]
@kathrynmsullivan looks like we've been duplicating our ODS updates between this ticket and #346. I can close out this one if we'd prefer to keep everything in #346
