### ISSUE TITLE
Expand scope for DQ outreach performed by CS team

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#321]
Coming out of conversations with Gillian, the CS team will be further help with data quality outreach.

- [x] Meet with Evan, Samantha, Amanda
- [x] Revise processes as needed
~Check in w/ E on data creation portion~
- [x] Figure out who the "LA 6" are
- [x] Finish Data Quality outreach scripts ~(may need to split out into its own issue)~ Keeping in this issue to track completion of formatting updates and all finalized scripts
- [x] Finish DQ03

**Comment by o-ram** [comment]
Will keep the finishing of the outreach scripts in this issue and close it once those are complete.

**Comment by laneymangan** [comment]
working session scheduled for 12/7

**Comment by laneymangan** [comment]
[DQ Outreach SOP can be found here](https://docs.google.com/document/d/1GoNCU5bC0RBq23fkDIdGlA60lCUVY9IHnii28YrkEPo/edit#heading=h.2xzb0r6ihpk1). I finished the first draft so I'm passing to @o-ram and @kathrynmsullivan for review and edits

**Comment by o-ram** [comment]
@laneymangan finished going through this and responded to any comments/made suggested changes. Let me know what you think! @kathrynmsullivan also feel free to take a pass

**Comment by laneymangan** [comment]
[DQ03 has been finalized](https://docs.google.com/document/d/1GoNCU5bC0RBq23fkDIdGlA60lCUVY9IHnii28YrkEPo/edit)

**Comment by laneymangan** [comment]
Reopening for @kathrynmsullivan to take a look

**Comment by AnthonyRollins** [comment]
@laneymangan When do you need this back? We can look to have this worked on in February but it can be done sooner if needed.

**Comment by AnthonyRollins** [comment]
@laneymangan currently, I have a Jan 22 - 26th timeline for this, should the be done before February?

**Comment by laneymangan** [comment]
We'd actually like to present this in our Account Manager meeting on February 1st, so any time before then is perfect. We might have more revisions after the 2/1 meeting, depending on input from the rest of the team.

**Comment by kathrynmsullivan** [comment]
@laneymangan & @o-ram - This is great. The process flow feels right to me.
