### ISSUE TITLE
Guide on how to use the Slack/Hubspot integration

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#322]
Now that Hubspot and Slack are connected, users can instantly create a note, task, or ticket in Hubspot within slack. This will be very helpful for most of Cal-ITP and needs a training guide on how people can do this. May be a good use case for a video walkthrough.

**Comment by AnthonyRollins** [comment]
@o-ram I can create a Scribe for this, and take this off of others to work on this. Let me know if that makes sense to still create.

**Comment by AnthonyRollins** [comment]
@o-ram Created two new scribes to showcase the Hubspot/Slack integration.

- [Add a note to a contact](https://scribehow.com/shared/HubspotSlack_Integration_Add_a_note_to_a_Contact__hw6lDGcYTxOhbQwEhITgfQ?editmode=true&desktoprecorder=true)
- [Add a association to a company](https://scribehow.com/shared/Slack_Workflow__e2d4UTF4SPiy0NtfFj1S-w?editmode=true&desktoprecorder=true)

**Comment by laneymangan** [comment]
@AnthonyRollins @o-ram I reviewed both guides. I added some clarifying text but overall looks good! I'll go ahead and add this to our training guide tracker

**Comment by AnthonyRollins** [comment]
Thanks, @laneymangan. I will close this out.
