### ISSUE TITLE
[New User Request]: 

### ISSUE THREAD

**Issue by SLewis1120** [cal-itp/customer-success#323]
### Email address

samantha.lewis@dot.ca.gov

### Full name

Samantha Lewis

### What do you I want to do in Hubspot

- [ ] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [ ] Access a Deals pipeline _(payments, data assessments, etc.)_
- [X] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

Yes

**Comment by AnthonyRollins** [comment]
The invite link was sent; let me know if you need help.
