### ISSUE TITLE
[New User Request]: Amanda Ha

### ISSUE THREAD

**Issue by amandaha8** [cal-itp/customer-success#324]
### Email address

amanda.ha@dot.ca.gov

### Full name

Amanda Ha

### What do you I want to do in Hubspot

- [ ] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [ ] Access a Deals pipeline _(payments, data assessments, etc.)_
- [X] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

Yes

**Comment by AnthonyRollins** [comment]
@amandaha8 Invite sent - check your email from an invite from Hubspot
