### ISSUE TITLE
Form for customer anecdotes

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#328]
Draft a form for others on the Cal-ITP team to fill out when they have a customer anecdote/quote to contribute. This will make our monthly reports much easier and expands the amount of places we get anecdotes from.

Initial thought is for this to be a simple Hubspot form, but can be discussed.

We have made this form, tested it, and included it in the monthly report. Last task to be completed before closing:
- [ ] announce in customer success channel and pin form to channel

**Comment by AnthonyRollins** [comment]
@o-ram Hubspot form seems fine with me.

**Comment by o-ram** [comment]
@AnthonyRollins in light of recent developments, any change in thoughts on where the form lives? In the spirit of keeping things as-is while we figure things out, a HubSpot form still makes sense to me, and this would be pretty quick to set up. But if you'd rather go with something like a Google Form, I am open!

**Comment by AnthonyRollins** [comment]
Let's keep it to Hubspot - that makes the most sense.

**Comment by AnthonyRollins** [comment]
@o-ram Created the first draft of this [form](https://app.hubspot.com/feedback-editor/5519226/custom/8/survey). I've assigned the anecdotes form to @kathrynmsullivan @laneymangan to review

**Comment by laneymangan** [comment]
Looks good to me! Made a couple very very minor edits but other than that I think it looks great.

**Comment by kathrynmsullivan** [comment]
Reviewed & looks good!

**Comment by laneymangan** [comment]
@AnthonyRollins I had a thought: should we add an option to input the date/month that the anecdote took place? Not sure how strict we plan to be about only reporting stories from that specific month. 

Also, is this where our direct team (ie me, olivia, kat, you) should input anecdotes? Or would you rather us continue to put them directly into the report slidedeck? (CC @o-ram @kathrynmsullivan)

**Comment by o-ram** [comment]
Yes, I like that idea! Will add it.

On the second question, I think so! I plan to because I always forget things by the time the monthly report rolls around and then they will all be in one place.

**Comment by o-ram** [comment]
@laneymangan date question added! LMK what you think.

**Comment by AnthonyRollins** [comment]
@o-ram This looks great!

**Comment by o-ram** [comment]
Yay! [Survey is published](https://survey.hsforms.com/1OivFBobeSLSMTVjBoETyXg3aanu) and can be used starting now! I will draft a message to share across Cal-ITP. Also planning to pin it to the CS channel in slack.

**Comment by AnthonyRollins** [comment]
@o-ram I believe we can close this issue off as we now have a way to add this to the 017Q monthly reports, and it looks like we just need to announce this, which I think we mention to others, right?

**Comment by o-ram** [comment]
I need to double check the form because I was supposed to add a question regarding if the anecdote was approved for sharing or not, and I cannot recall if I did that. After that, I think a Slack message might still be helpful just to make a more official announcement because testimonials are all the rage right now, and it's a good first step to let people know we've been thinking about the process. All to say - I'd like to leave this open a bit longer but will close it by the end of Jan. for sure.

**Comment by o-ram** [comment]
v1 of the form is complete for internal use and an announcement has been made in slack.

- [Form link](https://share.hsforms.com/1tLqX8QCDThuHS1au2RGIdA3aanu)
- [Submissions](https://app.hubspot.com/submissions/5519226/form/b4ba97f1-0083-4e1b-874b-56aed9118874/submissions/)
- [slack announcement](https://cal-itp.slack.com/archives/C03S1FDGZ2A/p1707251476554109)
