### ISSUE TITLE
[New User Request]: 

### ISSUE THREAD

**Issue by unreasonableman** [cal-itp/customer-success#329]
### Email address

kay.neuenhofen@dot.ca.gov

### Full name

Kay Neuenhofen

### What do you I want to do in Hubspot

- [X] Email contacts at transit agencies
- [X] Batch email contacts from multiple agencies
- [ ] Access a Deals pipeline _(payments, data assessments, etc.)_
- [ ] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

None

**Comment by AnthonyRollins** [comment]
Invite sent to [kay.neuenhofen@dot.ca.gov](mailto:kay.neuenhofen@dot.ca.gov)
