### ISSUE TITLE
Unexpected Conference Expenses

### ISSUE THREAD

**Issue by kathrynmsullivan** [cal-itp/customer-success#339]
This issue is to provide a place to document any unexpected expenses to attend the conferences so future budgets can be accurate. 

1. Pre-conference activities: Ex: CALACT has two extra days prior to the expo. These seem to be networking activities, like golf. 
2. Furniture rental: Chairs, carpet, tables. Not every 8x10 booth is the same. Most booths come with a table but that is not always the case. After registration, you are sent a password-protected "exhibitor kit"  where you see what is included in your booth registration, and then go from there.

**Comment by kathrynmsullivan** [comment]
Added actual costs [column](https://docs.google.com/document/d/10mIYRtbQLFFmPjy5UDvE7F2eI_lC3n39b3r5_AnJDVE/edit) to our proposal for fall conferences

**Comment by AnthonyRollins** [comment]
Furniture ordered.

**Comment by AnthonyRollins** [comment]
We can close out this issue as we have ordered everything.
