### ISSUE TITLE
Review CRM issues to pause

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/customer-success#343]
There is a need to review existing github issues to ensure they are all still relevant. Where they are not relevant, we can put them on pause until further notice.

**Comment by AnthonyRollins** [comment]
A few items that I think should be put on pause:
- [ ] #187 
- [ ] #127 
- [ ] #299 
- [ ] #210 
- [ ] #183 
- [ ] #152

**Comment by laneymangan** [comment]
Have a couple follow up questions on some of the below, but leaving these here for now:
- [ ] https://github.com/cal-itp/customer-success/issues/301
- [ ] https://github.com/cal-itp/customer-success/issues/306
- [ ] https://github.com/cal-itp/customer-success/issues/264
- [ ] https://github.com/cal-itp/customer-success/issues/152
- [ ] https://github.com/cal-itp/customer-success/issues/271
