### ISSUE TITLE
Elevator Pitches Concise Overviews

### ISSUE THREAD

**Issue by kathrynmsullivan** [cal-itp/customer-success#344]
- [x] 1st draft of Pitches
- [x] 1st Review
- [x] Final Draft

Link to google [doc](https://docs.google.com/document/d/1ZiTWAVp0ojA6LSe-SDRF2xXhfJqbI9Jd3vMEqK4BeA4/edit)

**Comment by kathrynmsullivan** [comment]
1st draft is complete @o-ram @laneymangan @AnthonyRollins . There might not be time this week for a review. Maybe next week one of y'all can review it?

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan Added some comments and edits to the doc. Let me know if you need anything.
