### ISSUE TITLE
Adding an Agency to Cohort

### ISSUE THREAD

**Issue by kathrynmsullivan** [cal-itp/customer-success#347]
Create a process that creates the criteria an agency possesses to be added to a cohort. 

10/5: Brainstorm document can be found [here](https://docs.google.com/document/d/131jVMGjvB2DtZ8Ih5ZPENVDct56Fh1vKr-ezJ0bm32c/edit)

**Comment by AnthonyRollins** [comment]
We can close this out as we move into a tier program. @kathrynmsullivan, is there any reason we shouldn't close this issue?
