### ISSUE TITLE
[New User Request]: 

### ISSUE THREAD

**Issue by csuyat-dot** [cal-itp/customer-success#348]
### Email address

christian.suyat@dot.ca.gov

### Full name

Christian Suyat

### What do you I want to do in Hubspot

- [ ] Email contacts at transit agencies
- [X] Batch email contacts from multiple agencies
- [ ] Access a Deals pipeline _(payments, data assessments, etc.)_
- [ ] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

Not sure

**Comment by AnthonyRollins** [comment]
@csuyat-dot invite sent
