### ISSUE TITLE
Agency Tiers

### ISSUE THREAD

**Issue by kathrynmsullivan** [cal-itp/customer-success#353]
This issue is a placeholder for brainstorming a tier system for transit agencies. There are 189 fixed route bus agency operations.

**Comment by AnthonyRollins** [comment]
@laneymangan will schedule a meeting with Erika, and the rest of the Customer Success team.

**Comment by laneymangan** [comment]
Meeting scheduled for 12/7

**Comment by o-ram** [comment]
Framework for number/type of tiers described in this spreadsheet.

Next steps:
- Number exercises to see how many agencies of each tier a full time AM should be expected to handle vs part time AM.
- Meet with Jeremy and Erika (scheduled for 1/4/24)

**Comment by laneymangan** [comment]
Meeting scheduled for 1/11 to review updated plan with Jeremy and Erika + CS team.

**Comment by o-ram** [comment]
Tier spreadsheet has been updated based on feedback, ratios have been included, and I've started to play with the numbers for assignment/workload breakdown with the ratios factored in. 2 "clean" tabs were created for Jeremy and Erika to review.
