### ISSUE TITLE
Conference retro

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#358]
This issue is meant to capture the ideas and suggestions for improving Cal-ITP's presence at conferences.

## Conference booth
- [x] Create marketing one-pagers to sell Cal-ITPs work: Example: "Check out Caltrans MSA vendors for open loop"
- [x] Create a one-pager with a QR code to book a meeting with the Customer Success [team using Hubspot](https://meetings.hubspot.com/kathryn15/customer-success).
- [ ] Create stickers of the bus, schedule sign and contactless payment icons on calitp.org
- [ ] Look into a prize for people visiting our table
- [ ] Determine if it would be better to advertise Caltrans as the booth attendees on conference materials.

## Outreach
- [ ] Determine the right social media and email outreach campaigns leading up to the conference
- [ ] Send email blasts out to attendees: introducing ourselves, and letting people know they can find us at our booth number

**Comment by vykster** [comment]
[Instructions for LinkedIn and generating a QR code for your profile](https://www.linkedin.com/help/linkedin/answer/a525286/using-a-linkedin-qr-code-to-connect-with-members)

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan let's plan to meet on these items before we add to the conference roadmap #378. I will try to find sometime before we dig into the conference roadmap.

**Comment by AnthonyRollins** [comment]
Combine with roadamp #378
