### ISSUE TITLE
Include mention of conferences in next newsletter email

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#361]
Draft email text for the newsletter and pass it along to Angelly and Isaac for inclusion in the edition going out the morning of 11/7.

**Comment by o-ram** [comment]
@laneymangan @kathrynmsullivan @AnthonyRollins, draft of email for newsletter below - let me know if you have any edits. Short and sweet tends to be better for these but open to adding more. If possible, please review as soon as you can so I can get this to the newsletter team asap (for sure need to do so by EOD today).

Draft:

The Cal-ITP Customer Success team had a great time getting to meet many of you in person at the CALACT 2023 Autumn Conference last week! If you missed them, come see them in Pasadena at the [California Transit Association Annual Fall Conference and Expo](https://caltransit.org/Events/Annual-Conferences/Fall-Conference-Expo) from November 15-17. They will be at **booth #703** in the Expo Hall and are excited to engage with you and answer your questions about open-loop payments, GTFS, and how Cal-ITP can help your organization!

**Comment by kathrynmsullivan** [comment]
Love short and sweet. I made tiny changes but ignore it if feels incorrect: The Cal-ITP Customer Success team had a great time **meeting** many of you in person at the CALACT 2023 Autumn Conference last week! If you missed them, come see them in Pasadena at the [California Transit Association Annual Fall Conference and Expo](https://caltransit.org/Events/Annual-Conferences/Fall-Conference-Expo) from November 15-17 **at booth #703 in the Expo Hall. They are** excited to engage with you and answer your questions about open-loop payments, GTFS, and how Cal-ITP can help your organization!

**Comment by laneymangan** [comment]
looks good to me!

**Comment by AnthonyRollins** [comment]
Looks good to me.

**Comment by o-ram** [comment]
Thanks, all! And yes @kathrynmsullivan you are correct, thanks a ton for editing and catching my mistakes!
