### ISSUE TITLE
Develop list of agencies for payments team re. Genfare and cashless

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#362]
Many agencies have asked what Cal-ITP is doing about genfare/fare collection, with some taking different approaches to it. We think it would be helpful to put a list together for the payments team as they decide on their next steps in this space. This issue is for brainstorming and finalizing that [list](https://docs.google.com/document/d/14vI6fZvZ2kF1TZoyLiI8gJNNzI-oYIC_Z3Tfzvg8YJ8/edit).

**Comment by laneymangan** [comment]
- Victor Valley
- Glenn County

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan Will add the spreadsheet doc

**Comment by o-ram** [comment]
Per Payments team, this would be very helpful for them to have. CS team to pick up this effort as a priority again in Jan. 2024.

**Comment by AnthonyRollins** [comment]
We can fit this in February. Do you think we should pick this up sooner @o-ram? I'm curious if agencies are still asking about this, @laneymangan @kathrynmsullivan, and how often.

**Comment by laneymangan** [comment]
Yeah, this is an ongoing issue among transit agencies. We've been checking in regularly with the payments team and GG about this issue, Rebel is building out a WT for this. Adding notes from meetings last month here: 

**Customer Relations / GG Meeting**
```
-Lilly is working on a WT for what to do about Genfare and cash
-We may need to invest time in finding a cheap cash fare box that agencies can purchase. Use this as a solution
```
**Payments Team Meeting**
```
Genfare check in:
-Cohort of agencies payments team is hoping to go through structured process with to help them move away from fare box
-Challenge depends on how quickly agency wants to move
-Get them to think about the breadth of their fare products
     -Can you get rid of anything?
     -Thoughts on cash?
-Cohort is open - aiming for 4 which was the goal but could have more
     -Long Beach, MST (want to move fast so may fall out)
     -VCTC? Is Gold Coast a part of them? 
     -Victor Valley
-Cohort will be a 2024 program
     -CS pick back up task to create “genfare” list
     -CS team list - yes!
```

**Comment by AnthonyRollins** [comment]
So, it sounds like this won't be until March based on the need for a new WT for this.

**Comment by o-ram** [comment]
The new worktask starts Feb 1st and they will be looking for agencies to work with, so we should get this done sooner than later, preferably within the first few days of Feb.

**Comment by AnthonyRollins** [comment]
@laneymangan Adding genfare agencies will be developed in #389.
