### ISSUE TITLE
[Data Import]: Press data by district

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#365]
Add new press lists to the Hubspot Press list.
- Central Valley media list (District 6) import [data](https://docs.google.com/spreadsheets/d/16me_kI6-EzXeyQfbZrwqKxGuBT3jS7tzb_4WNYKPq8M/edit?usp=drive_link)
- Inland Empire (district 8) [media list](https://docs.google.com/spreadsheets/d/1-P0SsU_WtmxFbXRiTnWbwQvXbsaPB_XQS8hT03zLhjE/edit?usp=drive_link)

## To-Do
- [x] Add press `job_role` tag to all press contacts
- [x] Add district data to all data

**Comment by AnthonyRollins** [comment]
@ProvvidenzaC When these data files are ready, could you send the links here so I can import them into Hubspot?

**Comment by AnthonyRollins** [comment]
@ProvvidenzaC will add the data into Hubspot on Jan 3rd.

**Comment by ProvvidenzaC** [comment]
@AnthonyRollins these have been uploaded to Hubspot.
