### ISSUE TITLE
Adding in vendor information to company profiles

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#374]
As a part of building out company/agency profiles into Hubspot, we should have basic vendor info included as a property. Right now, we have to switch back and forth between Hubspot and Airtable if we want to know what vendor an agency has for a certain piece of technology. Adding this info into Hubspot would make the workflow for the CS team easier and increase visibility across Cal-ITP.

I think we can do an export from Airtable and import into Hubspot, but should be explored.

Brainstorm list:
- CAD/AVL
- GTFS
- Scheduling
- Fare box
- Data plans/connectivity

**Comment by AnthonyRollins** [comment]
@o-ram Let's put this on hold for now as we are looking into getting custom objects. We would still need a property like this, but it wouldn't be associated with a Company record.

**Comment by AnthonyRollins** [comment]
@laneymangan I want to ensure you saw this when building your CRM vendor profiles doc.

**Comment by laneymangan** [comment]
thanks for flagging! all of the items in the brainstorm list are included in the spreadsheet
