### ISSUE TITLE
Send email blast to announce GTFS-RT RFP

### ISSUE THREAD

**Issue by mrose914** [cal-itp/customer-success#377]
**Overview:** The GTFS-RT RFP is almost ready to share. We have developed the content below and sent to DGS for approval. We are awaiting their approval, at which point we should send the email out.

**Email Subject Line:** DGS releases RFP for GTFS-Realtime software

**Email Sender:** hello@calitp.com

**Recipient list:** All newsletter recipients

**Email Template / Copy:** See copy [here](https://docs.google.com/document/d/1o3LmawMA1GJ09ZE4jq2SoSLQp8uoVhrUD60SUVYDKnQ/edit)

**Comment by o-ram** [comment]
In the event DGS releases the RFP before the end of the year, Erika has agreed to hit "send" on the email blast while I am out of the office. I have prepped the copy in constant contact, so all that needs to be done is insert the link and make any changes requested by DGS.

**Comment by o-ram** [comment]
Email blast has been sent to all newsletter recipients, requested vendors, and Mobi Mart sign ups.
