### ISSUE TITLE
Conference RoadMap

### ISSUE THREAD

**Issue by kathrynmsullivan** [cal-itp/customer-success#378]
Design a Conference Roadmap for 2024-2025 year for CS Team. Utilizing the [conference review](https://docs.google.com/document/d/18yo6lCqo9kk0FvbNA1T27CL9z1KL6jGdlP7ym0KW7Vg/edit) document, the goal is to create a roadmap we can use as a template going forward

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan CalACT registration is out, so we should start planning this roadmap asap

**Comment by kathrynmsullivan** [comment]
@AnthonyRollins - ready for review, assigning to you :)

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan, I looked at your roadmap, and I think it has everything we need to prep for. Could you create that roadmap using Github Issues so we can add some due dates to each phase and know when we need to begin working on various items?
