### ISSUE TITLE
Build out Vendor property details

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/customer-success#382]
1/16 Update: we will instead be upgrading Hubspot to enterprise level, allowing us to create Custom Objects. We will create a Custom Object called "Vendors" which will address this need.

We'd like to break up the "vendor" company type property into more defined options. This will help us in identifying and filtering the many types of vendors that we work with. Current break down ideas will be kept here for now:

Vendor types: 
Manufacturer
Software
Hardware

**Comment by laneymangan** [comment]
[Vendor spreadsheet](https://docs.google.com/spreadsheets/d/1joJR8dZ6b6miE2AFcCHPLYocnhOEKoHDsFQVK8gNJxc/edit#gid=0)

**Comment by AnthonyRollins** [comment]
Similar to #374. @laneymangan, I hope we can finalize the research for this (meet with other Cal-ITP members) in the next 2 weeks. Let me know if we need more time to look into this?

**Comment by laneymangan** [comment]
I think 2 weeks is reasonable

**Comment by laneymangan** [comment]
List of next steps
- [ ] confirm vendor priorities with Scott
- [ ] confirm vendor priorities with Marissa
- [ ] confirm vendor priorities with E
- [ ] create vendor github milestone
- [ ] finalize vendor properties
- [ ] figure out API for logging past activities
- [ ] prep import

**Comment by o-ram** [comment]
@laneymangan This is looking great! I am 100% on board with consistency, so I support using these labels, and they make sense to me. And I _love_ that we can create custom conditional properties for a specific vendor type if we want to get more detailed. A few thoughts:

- I vote for keeping `Transit Operations`, as my guess is they are using this to describe a company that provides the literal operations for a provider - IOW, the drivers. This is an important piece of info as it does impact how we interface with the provider on projects. If I'm wrong and that is not what they are using `Transit Operations` for, let me know!
- We should decide now if we want one pipeline called `MSAs` that we just keep adding stages to as more contracts get added to Mobi Mart, or if we want different pipelines based on the MSA subject, i.e. one pipeline for payments contracts and a separate pipeline for GTFS-RT contracts (when that comes). I haven't thought about this enough to have a strong opinion either way, but it feels like something we should pick a stance on.
- I know you already said you're working on descriptions for the categories, but I just wanted to echo that I think documenting as much as we can here is helpful, as it's likely everyone who looks at these won't commit to memory everything in parenthesis next to a vendor type. Meaning if someone looks at a profile and sees the vendor type is `onboard rider comms`, we should make sure that we clearly state what all that includes somewhere for reference.

**Comment by AnthonyRollins** [comment]
@laneymangan Is there still more work we are doing here? Should we pass this off to @adamglinder-la or close this out for now?

**Comment by laneymangan** [comment]
I'll go ahead and close this out as the initial scope is complete
