### ISSUE TITLE
Convert CS Benefits onboarding guide into a Hubspot form

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#388]
- Convert google doc into Hubspot form so agencies can fill it out themselves and answers are saved in Hubspot.
- Set up workflow for after form is filled out so that the appropriate parties are notified and the form answers go where we want them too.

**Comment by o-ram** [comment]
Draft has been started. This effort will be picked back up in Jan. 2024

**Comment by AnthonyRollins** [comment]
@o-ram How important is this issue to get up and running?

**Comment by o-ram** [comment]
I think this can be slotted for August - I'm aiming to get the Benefits pipeline done before I go on vacation which is more important than this. Additionally, we might tweak the onboarding process a bit which could influence what is in the form.

**Comment by AnthonyRollins** [comment]
@o-ram Great! I added to August, and marked it with a `low` priority.

**Comment by o-ram** [comment]
Closing issue: Form is created, tested, and was used in a recent agency onboarding. The answers to their form populate the associated company's deal in the Benefits pipeline. The completion of the form does not trigger any specific notifications yet, that is TBD based on the overall structure of the pipeline.
