### ISSUE TITLE
[New User Request]:  Vivek

### ISSUE THREAD

**Issue by vevetron** [cal-itp/customer-success#395]
### Email address

vivek.bansal@dot.ca.gov

### Full name

Vivek Bansal

### What do you I want to do in Hubspot

- [ ] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [ ] Access a Deals pipeline _(payments, data assessments, etc.)_
- [X] Respond to support tickets
- [X] Not sure

### Do you need training on how to use Hubspot?

No

**Comment by AnthonyRollins** [comment]
@vevetron You should receive an email from Hubspot with login instructions.
