### ISSUE TITLE
CALACT 2024: Travel Request 

### ISSUE THREAD

**Issue by kathrynmsullivan** [cal-itp/customer-success#397]
- [x] Review CA travel requests
- [x] Review Heather's Spreadsheet
- [x] Submit travel request

**Comment by kathrynmsullivan** [comment]
Hotel: You will receive the hotel registration link in your confirmation order.
“The Conference Hotel is Paradise Point located at 1404 Vacation Road, San Diego, CA 92109. Single room rates are $239.00 per night if booked by March 13, 2024. The room block will close on 3/13/2024 and rooms will be on a space available basis.”
Expo hall $1,975.00 + 3 tickets $2,025.00 = $4000.00
Review California state travel requests
Create github issue for each CS member to submit a travel request
Travel request form must now include estimated labor hours
Ticket registration
Access code: MEMBER24

**Comment by AnthonyRollins** [comment]
Resubmit the budget for new hires to attend the conference.

**Comment by AnthonyRollins** [comment]
Travel requests will need to be submitted for Jess and the new hires. Creating a new issue to track that work for next month
