### ISSUE TITLE
[Deals Pipeline Request]: GTFS-RT

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#401]
### Deals Pipeline Request

GTFS-RT

### Who needs access?

All users should be able to view

### What problem are you trying to solve for?

Lack of a home for showing agencies who could benefit from or are interested in the RT campaign.

### What is the goal of the pipeline you are trying to solve for?

A list of agencies we want to target once the outreach campaign for gtfs-rt kicks off.

### What stages would you like in the pipeline?

Prospect, Interested, TBD after that

### Have you used an exisiting pipeline in Hubspot?

Yes

**Comment by laneymangan** [comment]
[GTFS-RT Pipeline has been created](https://app.hubspot.com/contacts/5519226/objects/0-3/views/all/board)

**Comment by laneymangan** [comment]
@o-ram the GTFS-RT Airtable list has been imported into the GTFS-RT pipeline under "Prospect"

**Comment by o-ram** [comment]
Thanks @laneymangan, this looks great to me! I think you can close this one out - we can't really do anything more at this time.
