### ISSUE TITLE
Verify sending domain for Hubspot Marketing

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#402]
I received a notification that our email-sending domain needs to be verified. See screenshot.

![Image](https://github.com/cal-itp/customer-success/assets/25047205/fa7db99d-4854-4ecf-bea8-52269798747e)

We are trying to send out our first CS newsletter in February, so we are hoping to resolve this before we send the first email.

**Comment by thekaveman** [comment]
These records are now updated in our DNS, and Hubspot appears to be in good shape:

![image](https://github.com/cal-itp/customer-success/assets/1783439/7a250042-6575-4a37-be81-a9387d73af82)

More details in [this Slack thread](https://cal-itp.slack.com/archives/C015B2EBHU0/p1706750142524769).

Please let me know (tag me!) if you see any more error messages / issues within Hubspot.
