### ISSUE TITLE
Testimonial strategy planning for 2024

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#403]
In 2023, the CS team started to informally collect positive anecdotes from agencies. These quotes were used in our monthly reports but were never gathered with the intent of using them in external-facing materials. Towards the end of 2023, the need for having approved testimonials that could be used in materials became apparent. That need continues into 2024 from both the comms team and the website team. Therefore, we need to be more organized and thoughtful about collecting testimonials this year.

Wishlist from Jan. 2023 comms meeting:
- Build a bank of testimonials to pull from across efforts
- Story banking and human interest stories are powerful (something like "customer stories")
- Supportive anecdotes and direct quotes from agencies (and riders - though we all acknowledge that is out of our control)
- Can CS think about how to actively ask for permission to use the quotes that they are saying live in interactions

Completion of this issue will look like CS having a strategy that meets the needs of other teams and has been communicated across Cal-ITP.

**Comment by o-ram** [comment]
@laneymangan, @kathrynmsullivan, and I spoke about this on 1/29 and our initial steps include refreshing the anecdote form (#328) and organizing the view where form responses live. This will help solve the request to build a bank of testimonials.

**Comment by o-ram** [comment]
@mrose914 Laney is going to schedule time for us to chat about this now that we are past CALACT!

**Comment by laneymangan** [comment]
Meeting scheduled for 5/16
