### ISSUE TITLE
Account Manager onboarding list audit

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#408]
In preparation for a new account manager, we want to review/audit the list of onboarding tasks from the past:

General Cal-ITP information:

-  [Cal-ITP “Start Here” guide](https://docs.google.com/document/d/1dpjjNSdmnAejpsw4RAdbNzFBOdxlNO_-1KWxwb96cVI/edit)
-  [Caltrans Strategic Plan](https://dot.ca.gov/-/media/dot-media/programs/risk-strategic-management/documents/sp-2020-16p-web-a11y.pdf) (Optional, For high-level understanding of what’s happening at Caltrans)
-  [PMP Strategic Plan](https://dot.ca.gov/-/media/dot-media/programs/planning-modal/documents/pandmp-sp-2020-24-a11y.pdf) (Optional, For high-level understanding of what’s happening at Caltrans)
-  [Interview with Gillian](https://www.intelligenttransport.com/transport-articles/131081/california-taps-into-the-future-of-fare-collection/) (Cal-ITP Program Manager/Chief of Caltrans Division of Data and Digital Services)
-  [About Cal-ITP standard deck](https://docs.google.com/presentation/d/1Yi0zdZ3uiQ9XyiPfePRW4Dtu-ALiP12YFqXD5Xv_LoI/edit?usp=drive_link)
-  Roadmap (link needed from Jess)
-  https://github.com/cal-itp/customer-success/issues/188
-  [CRM Guide](https://docs.google.com/document/d/11SIWzGqDDJN4OADASiXywvcu9C8deXZRvTE-cdn-Lh4/edit#heading=h.q9i1mqgcc13q) (Optional, Do not need to read all of it right away, but helpful to have at hand as familiar with how we use HubSpot increases)
-  Obtain a HubSpot account
-  Make a Github account

Customer Success team/Account Manager information:

-  [Account Manager Training Guide](https://docs.google.com/document/d/18u62_Cz9DV3UqrlAreXqpbirlo0cN4KzWONfDLrTKrE/edit#heading=h.cfwavlj00dpn) in its current state
-  [Team OKRs](https://docs.google.com/document/d/1a5_pRT1mb_MWpgxPRiVxpMwiMQ7JAdhdAa7m9jidSms/edit)
-  [Customer Success philosophy](https://docs.google.com/document/d/1Pe4P6qoD8O-YLP0BJLpqSYaYxBv-9oOMucDbyqLzwMM/edit?usp=drive_link)
-  [Menu of Services](https://docs.google.com/document/d/118-tOm14bgIWXtiBx_rZ-Picxdv9JqpD4PS7WXjkoiM/edit)
-  Google Drive: [Customer Success folder](https://drive.google.com/drive/folders/17WChuEjB4_veWBlSW5uhhWpH33_N6EId) and [SOP folder](https://drive.google.com/drive/folders/150-ZfnfjdYp69eYqEoNyRBWSN2ZK2YPG)
-  [Cohort list](https://app.hubspot.com/contacts/5519226/objects/0-2/views/13178995/list?redirectFrom=crm-records-ui)
-  [Doc Catalog](https://docs.google.com/document/d/1cowfa-l3x4blDkrF8I6WmN7NHEGQHYV_8MemE0a7CUc/edit#heading=h.gtlbgaln0owh) (this is a work in progress - specific SOPs that are important now will be conveyed)
-  Agency list (introductions will come ~ week 3. For now, start with getting familiar with your assigned agencies.)
- HubSpot account needed. Once one is created, Olivia will assign Kathryn and link here to that subset of agencies.
- Read through https://github.com/cal-itp/customer-success/issues/290
- There is no one doc that conveys this, so this will take the place of a call where we can screenshare and provide some informal do's & don'ts as well as some helpful tips to keep in mind or have bookmarked.

**Comment by kathrynmsullivan** [comment]
@o-ram - here are some of my thoughts! Side Note: [This is the meeting notes](https://docs.google.com/document/d/1rwL5eqwjL10UslBIyWncye-Al-uSuSWXhPwDk93rgS0/edit) from the onboarding Brainstorm meetings Vyki, Sarah & I did. 

most helpful
-  Videos: Watch the all hands. In my onboarding meetings with Vyki & sarah, [this youtube channel](https://www.youtube.com/playlist?list=PLJA3syyg1ijm36JFZ95v79zAuv-5c8hfZ) would be a great addition for new Account Managers
- Jess's Doc on Cal-ITP. Her presentation from the October retreat would be amazing too! 
- Met with Kegan Day #1 to set up tech. Very helpful

what wasn’t useful
- Not having 1:1's with You and other Compiler folks scheduled. If people would be open to presenting their October Compiler retreat presentations to the new hires, that would be a great way to meet the team and gain deeper understandings.
- It would be helpful to have more check in's with the CS team the first two weeks. 
 
what is not needed right away
-Caltrans Strategic Plan
-PMP Plan

**Comment by AnthonyRollins** [comment]
Thanks, Kathryn, this is super helpful. @ProvvidenzaC I want to make sure you see Kathryn's input.

**Comment by AnthonyRollins** [comment]
@ProvvidenzaC I feel like we can close out this issue, unless there was some docs or thoughts you want to capture for next time.
