### ISSUE TITLE
[Property Request]: Tier

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/customer-success#409]
### Name of Custom Property

Tier

### What is the problem that this is solving?

As part of our new Agency Tier process, we need a way to distinguish between the different tier levels. This property will allow us to assign a tier to each agency in our program. 

### Object Association

Companies

### If you chose Company in the question above, which company type does this information apply to?

- [X] Transit Agency
- [ ] Vendor
- [ ] N/A
- [ ] Unsure

### If you chose Deal in the question above, which pipeline does this information apply to?

- [ ] Payments Pipeline
- [ ] Contract Outreach
- [ ] MDIP Outreach
- [ ] GRaaS
- [ ] Cubic/Umo API Key Outreach
- [ ] Cal-ITP Benefits
- [ ] Software for Scheduling
- [ ] Payments Dashboard
- [ ] Relevant Pipeline has not been created yet
- [ ] N/A
- [ ] Unsure

### Who is responsible for updating and maintaining this property?

Each Account Manager will be responsible for updating this as part of their CRM profile maintenance

### Updating Cadence

Other

### When does this property need to be implemented?

2/6/24

### Not sure what you need?

None

**Comment by laneymangan** [comment]
This property has been created as a dropdown single select. I also added it to the Transit Agency Details conditional section within the Company Record view. 

Can someone (@o-ram @kathrynmsullivan or @AnthonyRollins) confirm if you are seeing it? I'm not sure if a "reset to default" is required. It should look like the image below (ie you should see `Tier` under `Account Manager`)...
<img width="361" alt="image" src="https://github.com/cal-itp/customer-success/assets/107429473/94975b08-13f4-42de-b4ec-5605383302f4">

**Comment by o-ram** [comment]
@laneymangan I can see it!
<img width="463" alt="Screenshot 2024-02-06 at 1 14 18 PM" src="https://github.com/cal-itp/customer-success/assets/92001064/da4de986-2578-480d-b650-d64c3fd231ca">

**Comment by laneymangan** [comment]
Awesome, thank you @o-ram! I'm closing this issue but let me know if I can help with the import
