### ISSUE TITLE
Import Vendor list

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/customer-success#414]
- [x] Assign new vendor categories in spreadsheet
- [x] Import list

[List can be found here](https://docs.google.com/spreadsheets/d/1joJR8dZ6b6miE2AFcCHPLYocnhOEKoHDsFQVK8gNJxc/edit#gid=65641320)

**Comment by AnthonyRollins** [comment]
@laneymangan, Did you need any help getting this data into Hubspot? I determined that everything looks set up correctly; the unique identifier is the property named `Domain`, so make sure to use that one when importing details.

**Comment by laneymangan** [comment]
Imported! @AnthonyRollins 
<img width="487" alt="image" src="https://github.com/cal-itp/customer-success/assets/107429473/af0173ba-964e-4f11-ad42-6fd1bed8f68b">

Next I'll work on the associations, association labels, and any other remaining properties. But since the vendors are in, the activity import can happen whenever. I'll update the dev team

**Comment by AnthonyRollins** [comment]
@laneymangan AMAZING! Everything looks great. We should delete the `vendor domain name` property so everyone knows to use `domain` as the unique property.

**Comment by laneymangan** [comment]
`vendor domain name` has been deleted. I'll close out this issue!
