### ISSUE TITLE
CALACT 2024: Prepare for Conference

### ISSUE THREAD

**Issue by kathrynmsullivan** [cal-itp/customer-success#418]
- [x] #425
- [ ] #426
- [x] Align Calendar's with HubSpot
- [ ] #433
- [ ] #424
- [x] #434
- [x] Confirm Delivery of Marketing Materials
- [ ] #427

**Comment by AnthonyRollins** [comment]
Customer Success team [meeting link](https://app.hubspot.com/meetings/5519226/link/6879184) has been created.
