### ISSUE TITLE
[New User Request]: Carlo Ramirez (D7 rep)

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#422]
### Email address

carlo.ramirez@dot.ca.gov

### Full name

Carlo Ramirez

### What do you I want to do in Hubspot

- [X] Email contacts at transit agencies
- [X] Batch email contacts from multiple agencies
- [ ] Access a Deals pipeline _(payments, data assessments, etc.)_
- [X] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

Yes

**Comment by AnthonyRollins** [comment]
Invite sent to user
