### ISSUE TITLE
Create Association Labels

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/customer-success#430]
Brainstorm list of association labels for Vendor relationships

**Comment by AnthonyRollins** [comment]
I moved this to May, let me know if this make sense, @laneymangan

**Comment by AnthonyRollins** [comment]
@adamglinder-la moving this to August. Let me know if we should move this further out.

**Comment by AnthonyRollins** [comment]
@adamglinder-la Curious if we have finished these association labels or if ther is more work here.

**Comment by adamglinder-la** [comment]
For the 200 Vendors in our custom object, the associations are complete, but I'd like to leave this open for the moment until I get a chance to do a thorough double checking one-by-one. I can prioritize that earlier this month.

**Comment by adamglinder-la** [comment]
This work is complete, and all vendors have their associated labels connected.
