### ISSUE TITLE
Create AM dashboards

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/customer-success#443]
- Report in hubspot for tracking how many agencies people have in what tier, how many agencies overall are in each tier
- Include something for engagement so we can see if agencies should move up or down - this would also help us with reviewing categories on a monthly or quarterly basis

**Comment by o-ram** [comment]
Version of this for bullet 1 is currently tracked within our [tiers spreadsheet](https://docs.google.com/spreadsheets/d/1qWzuW07Tbq05ww6p9iMGPUZ5d4eqkbwS/edit#gid=987042482). It will ideally be retired in favor of the more visual Hubspot report.

**Comment by laneymangan** [comment]
[Drafting report here](https://app.hubspot.com/reports-list/5519226/113027418/)

**Comment by laneymangan** [comment]
[Looking in to how to create report that tracks changes in tiers over time](https://community.hubspot.com/t5/Dashboards-Reporting/Creating-a-report-on-the-change-in-history-of-a-custom-property/m-p/824617)

**Comment by o-ram** [comment]
@laneymangan do you think we can close this? I think we completed this with the [Agency tiers dashboard](https://app.hubspot.com/reports-dashboard/5519226/view/12813583) but if there was something else we wanted to do then we can leave it open.

**Comment by laneymangan** [comment]
I think we can close this. We can continue to adjust the reports if needed but since the original task is complete, I'll close it. Thanks for checking!
