### ISSUE TITLE
Create an issue template for making requests to send an email blast

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#448]
Create an issue template for requesting the CS team to send out email blasts

<ins>Content to include in template<ins>

This issue template can be used to request that the CS team send out an ad hoc email blast when Cal-ITP has noteworthy news to share. [The process for preparing an email blast is detailed in this document](https://docs.google.com/document/d/1FZBgW3vASHcPKmdD38V3zexcBNtyz-jZnjHQcwf4HBU/edit).

[Req. field] **Link to the email copy**:
_This should be a google doc link_

[Req. field] **Is the copy finalized?**:
- [ ] Yes
- [ ] No

_If no, the CS team will wait to take action on this issue until told that the copy is final._

[Req. fields] **Confirm that the linked document provides the following pieces of information**:
- [ ] Clear subject line 
- [ ] Pre-header (Optional, this is the line that shows up below the Subject Line in your mobile inbox. If your email has no pre-header, check this box anyway)
- [ ] A concise body 
- [ ] A signature at the end of the body (eg, From, The Cal-ITP Team)

[Req. field] **What email address should this be from?**:
- [ ] hello@calitp.org (preferred)
- [ ] calitp@dot.ca.gov
- [ ] Other

[Req. field] **Send Date**:

[Req. field] **Do you want to receive a test email?**:
- [ ] Yes
- [ ] No

**Please enter the names of anyone else who should receive a test email, if applicable:**

**Comment by AnthonyRollins** [comment]
@o-ram, I can take this one and create a draft PR that you can review and add changes.

**Comment by AnthonyRollins** [comment]
PR #459 is ready to merge after a final review from Olivia
