### ISSUE TITLE
Update CS Meeting QR code one-pager

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#449]
We have updated the QR code, which led to the link being updated. We need to update the QR code with [this new link from Hubspot] (https://meetings.hubspot.com/anthony-rollins/cs-conference-meetings). From there, we need to update the [one-pager](https://docs.google.com/document/d/1rHqVyEBXD1qG-tZpGWhEx5oZHLRNihoz9pS3A3Cuuqg/edit) so we can bring it to conferences.

**Comment by thekaveman** [comment]
@AnthonyRollins here is the new QR code image with a transparent background, LMK if this works or if we need to tweak (i.e. make larger etc):

![image](https://github.com/cal-itp/customer-success/assets/1783439/f42d2af2-e786-446a-bdb1-92ec902c4081)

I wrote a helper script and saved that to this repository to make this easier next time.

**Comment by AnthonyRollins** [comment]
Perfect! I added it to the doc, and it works great!
