### ISSUE TITLE
Draft Wrap up report - Account Management

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#451]
Follow the format in the [Program Development wrap-up report](https://docs.google.com/document/d/1IWJAVW2_Q890dJIL6EwV6Rsjr4S0JqYXiPC91CKpRSg/edit) to draft a report for Account management.  

**Framework**
- Add an overview section detailing high-level items
- Add 4-5 bullets on success or milestones hit
- Link additional reports and or documentation

**Comment by AnthonyRollins** [comment]
@o-ram We can talk more about this if you need me or have any questions.

**Comment by o-ram** [comment]
@AnthonyRollins [first draft complete](https://docs.google.com/document/d/1DDI7B-0bfCJSgh33Nv3bBZz8SCUXpDq8c0keYmAZoDA/edit), following the format of the 030A report. I tried to link to as many things as possible. Let me know what you think!

**Comment by o-ram** [comment]
Wrap up report has been moved to the work task folder for 030
