### ISSUE TITLE
Update subscription types in Hubspot

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#453]
Review the list of [subscriptions types](https://app.hubspot.com/settings/5519226/marketing/email/types) and remove any inactive or outdated.

**Comment by AnthonyRollins** [comment]
@o-ram I can review the subscription types and determine which ones we should remove.

**Comment by o-ram** [comment]
That would be great, thanks!

**Comment by AnthonyRollins** [comment]
@o-ram Subscriptions have been updated, so this page is ready for our following email.
