### ISSUE TITLE
Update conference interest form with new initiatives

### ISSUE THREAD

**Issue by mrose914** [cal-itp/customer-success#457]
We currently use [this form](https://app.hubspot.com/forms/5519226/editor/44e46b48-0d85-4d0b-a237-5c44a7132fd4/edit/form/field/0-1%2Finitiatives?redirectUrl=https%3A%2F%2Fapp.hubspot.com%2Fforms%2F5519226) to collect contact info at conferences. Given the addition of new products to our suite, we would like to add more options to the "Initiatives" field. 

Please add to "Initiatives" the following:

- GTFS-RT 
- ZEB Implementation 
- Software for Scheduling 
- Digital Signage

**Comment by AnthonyRollins** [comment]
I will get those added. @mrose914 did you have any preferences on the questions before? I will keep it pretty simple `name`, `email`, `company/org` and `which initiatives`. Let me know if there was anything else you were thinking of capturing

**Comment by AnthonyRollins** [comment]
@mrose914 @o-ram The form has been updated. Here is the live version: https://share.hsforms.com/1RORrSA2FTQuiN1xEpxMv1A3aanu. Let me know if there are any changes I should make.

**Comment by o-ram** [comment]
Looks good from the QR code as well! Just tried it on my phone
![IMG_6941](https://github.com/cal-itp/customer-success/assets/92001064/147c158e-a31e-4066-848e-22fbe51a3bd6)
![IMG_6942](https://github.com/cal-itp/customer-success/assets/92001064/0f08fd63-dffa-4d6d-b8e5-88f78d0b383a)
