### ISSUE TITLE
[New User Request]: Nina Dinh Hubspot Account

### ISSUE THREAD

**Issue by ninadinh-la** [cal-itp/customer-success#460]
### Email address

nina@compiler.la

### Full name

Nina Dinh

### What do you I want to do in Hubspot

- [X] Email contacts at transit agencies
- [X] Batch email contacts from multiple agencies
- [X] Access a Deals pipeline _(payments, data assessments, etc.)_
- [X] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

Yes

**Comment by AnthonyRollins** [comment]
@ninadinh-la Email invite sent.
