### ISSUE TITLE
[New User Request]: Adam Linder Hubspot Account New User Request

### ISSUE THREAD

**Issue by adamglinder-la** [cal-itp/customer-success#461]
### Email address

adam@compiler.la

### Full name

Adam G Linder

### What do you I want to do in Hubspot

- [X] Email contacts at transit agencies
- [X] Batch email contacts from multiple agencies
- [X] Access a Deals pipeline _(payments, data assessments, etc.)_
- [X] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

None

**Comment by AnthonyRollins** [comment]
@adamglinder-la Email invite sent.
