### ISSUE TITLE
[New User Request]: Marie Araneta

### ISSUE THREAD

**Issue by mariearaneta** [cal-itp/customer-success#462]
### Email address

marie@compiler.la

### Full name

Marie Araneta

### What do you I want to do in Hubspot

- [X] Email contacts at transit agencies
- [X] Batch email contacts from multiple agencies
- [X] Access a Deals pipeline _(payments, data assessments, etc.)_
- [X] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

Not sure

**Comment by AnthonyRollins** [comment]
@mariearaneta Email invite sent
