### ISSUE TITLE
Update tiers and Account Manager fields in Hubspot

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#463]
All agencies in scope for the tier system now have an assigned Account Manager. During this process, some initial tier assignments also changed. Therefore, we need to make sure that these records in Hubspot, reflect the tiers and names in [this spreadsheet](https://docs.google.com/spreadsheets/d/1qWzuW07Tbq05ww6p9iMGPUZ5d4eqkbwS/edit#gid=2018946141), which is up-to-date and accurate.

It should be decided whether doing an import to update these fields is needed or if updating the fields manually in Hubspot is feasible.

**Comment by laneymangan** [comment]
`Account Manager` and `Tier` properties have been updated
