### ISSUE TITLE
[New User Request]: Farhad Salemi

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/customer-success#474]
### Email address

farhad.salemi@dot.ca.gov

### Full name

Farhad Salemi

### What do you I want to do in Hubspot

- [ ] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [ ] Access a Deals pipeline _(payments, data assessments, etc.)_
- [X] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

Yes

**Comment by AnthonyRollins** [comment]
@evansiroky Invite link has been sent
