### ISSUE TITLE
Review brainstorm doc from CS team get together

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#475]
**[Brainstorm Doc](https://docs.google.com/document/d/1GJegQ_aea_8MMQRWOYpeTR3ZRGCOxSW6CLluDDJqo1Q/edit)**: 

After reviewing this doc... we need everyone to vote on slack poll. 

# To-DOs

- [x] marie to vote
- [x] Adam to vote

**Comment by adamglinder-la** [comment]
Looks like Enza, myself, Anthony, Marie, and Nina have voted. 

Just need:
- [ ] @laneymangan 
- [ ] @o-ram

**Comment by AnthonyRollins** [comment]
Final results from Slack poll
1. New Comms Strategies - How, where and why we share info, Pre-emptive collaboration to unify communication, Using Slack
2. Account Manager Narrative - Finding ways to "timeline" AM work with agencies and vendors

@ProvvidenzaC Could you suggest some next steps for us?
