### ISSUE TITLE
Draft Q2 CS Newsletter

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#476]
## Overview
1. Draft the next CS newsletter. 
2. Create new email draft in hubspot, duplicate [old newsletter](https://app.hubspot.com/email/5519226/details/154501874433/performance) 
3. There is a new list to send the newsletter to: https://app.hubspot.com/contacts/5519226/lists/88/filters

## TO-DOs
- [x] @ProvvidenzaC to draft newsletter
- [x] #477
- [x] @AnthonyRollins to review

**Comment by AnthonyRollins** [comment]
@ProvvidenzaC When should we expect a draft for this next report?

**Comment by ProvvidenzaC** [comment]
@AnthonyRollins Draft Test email sent your way and [here's a link too](http://5519226.hs-sites.com/-temporary-slug-7d9d3198-1a89-4438-8a17-d058c3374c9b?hs_preview=LPEsrYIo-167302033791)

**Comment by AnthonyRollins** [comment]
@ProvvidenzaC The Content looks good. Could we use a different background to change the design a little around Adam's written section?

**Comment by ProvvidenzaC** [comment]
Yep! Agreed. Will switch that up today!

**Comment by AnthonyRollins** [comment]
@ProvvidenzaC, Are we ready to send out the CS newsletter?

**Comment by ProvvidenzaC** [comment]
@AnthonyRollins Yes, reformatted Adam's section and sent a test email your way. Keep me posted when I should schedule! Hubspot wouldn't let me link it this time.

**Comment by AnthonyRollins** [comment]
@ProvvidenzaC I looked at the email, and it looks good to me. Please feel free to send this out.

**Comment by AnthonyRollins** [comment]
@ProvvidenzaC Did we get this sent out?

**Comment by ProvvidenzaC** [comment]
Thanks for checking in as this made me realize I didn't future schedule this correctly 3 weeks ago, so unfortunately no, but it is ready and can send this week if it's off cadence with the other newsletter.

**Comment by AnthonyRollins** [comment]
Yeah, please send it out when you can. It is fine if it is a little late. Let's plan for the next one to go out at the end of the quarter

**Comment by ProvvidenzaC** [comment]
This is scheduled to send tomorrow.
