### ISSUE TITLE
Draft 250 work summary of Calact

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#477]
Put in this google doc, make sure enza and the rest of CS team review you draft

**Comment by adamglinder-la** [comment]
@ProvvidenzaC 

[Here's the working doc of my summary.](https://docs.google.com/document/d/10wqeAkHlS5HJn3ogbDmhlMkulVKPOCPcsUjZDaPRpMo/edit?usp=sharing) Feel free to edit or add notes and I can adjust accordingly!

**Comment by adamglinder-la** [comment]
@o-ram @AnthonyRollins does anyone else need to know this is complete?

**Comment by AnthonyRollins** [comment]
Nope. @ProvvidenzaC can take it from here.
