### ISSUE TITLE
Email intros to transit Agencies post-CalACT 

### ISSUE THREAD

**Issue by ninadinh-la** [cal-itp/customer-success#478]
With the guidance and review of @laneymangan and @o-ram, @ninadinh-la will draft her first introductions as AM to CalACT attendees.

## first drafts needed for:

- [x] Valerie Cortez - City of Covina
- [x] George Calangeli - PVVTA
- [x] Nicole Soto - SBCTA
- [x] Sudesh Paul - City of Corona
- [x] Walter and Bryan - SunLine

### once draft is completed, Olivia or Laney will introduce on Nina's behalf, since DOT email is not accessible as of 5/14/24

**Comment by ninadinh-la** [comment]
@o-ram gave feedback on all drafts - thank you! I replied back with my final edits. They should be ready to send.

**Comment by laneymangan** [comment]
Emails have been sent to 
- Valerie Cortez - City of Covina
- George Calangeli - PVVTA
- Nicole Soto - SBCTA
- Walter and Bryan - SunLine

Olivia will handle outreach to Corona

**Comment by o-ram** [comment]
City of Corona has been sent!

**Comment by ninadinh-la** [comment]
thank you both @laneymangan @o-ram - since they're sent, I will close this.
