### ISSUE TITLE
Import data from LTSS 

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#482]
Data can be found [here](https://docs.google.com/spreadsheets/d/1swk3hTiiGnxMgrqQ-nzcL92PJXWCc_8bbhpLou1CP_U/edit#gid=0).

## To-Dos
- [x] Clean up name column to include only the name
- [x] Create columns for `first_name` `last_name` `email` `company_name` `company_domain`

**Comment by adamglinder-la** [comment]
@AnthonyRollins grid is clean. would you like me to import this into HubSpot as a list too?

**Comment by AnthonyRollins** [comment]
Yes, that would be great

**Comment by adamglinder-la** [comment]
Import into HubSpot complete, this list is titled [LTSS Members](https://app.hubspot.com/contacts/5519226/lists/92/filters)

> Out of the 71 rows provided in this import, we processed 71 records; 24 of the 71 records were newly created.

**Comment by adamglinder-la** [comment]
@AnthonyRollins can you please adjust Md Saiful Islam's user permissions in HubSpot to allow them to access lists?

also, I was poking around and don't think I have that level of admin access, but if I did, lmk how to find it in the future? thx!

**Comment by adamglinder-la** [comment]
@AnthonyRollins has fixed this issue and Saiful confirmed access to the List.
