### ISSUE TITLE
Begin intro emails for all agencies

### ISSUE THREAD

**Issue by ninadinh-la** [cal-itp/customer-success#483]
# send/schedule out intro emails in waves of ~10 agencies a week once DOT emails are accessible.
- [x] stay updated on DOT email access/tokens
- [x] create [tasks in bulk](https://docs.google.com/document/d/1jFX8HZYMCoZkVvmIu1jww9Slaf1QHbsco6F8RQvaXyI/edit#heading=h.tt5w0e6xbnb6) in hubspot
- [ ] draft out template emails for each agency

**Comment by ninadinh-la** [comment]
created task in hubspot for first 10 agencies, aiming to send these intros out by end of next week (5/23), DOT email access permitting.

**Comment by mariearaneta** [comment]
Completed creating tasks in bulk for my agencies following the ~10 per week standard.

**Comment by ninadinh-la** [comment]
### Update as of 5/23/24:

We are still waiting for DOT email access. For now, Marie and I will send intros using our compiler email, CC our DOT.

I boosted my emails from the intro emails post CalACT.

**Comment by ninadinh-la** [comment]
hi @o-ram and/or @laneymangan -- i think it would be most helpful for me to have my [general template](https://docs.google.com/document/d/1lHpUY9hcTI-dnOHMz-UIEYVRo8Ue-JpwuUpmQsJJsUU/edit?usp=sharing) be reviewed, then I can use it to adjust as needed with the general intros/ add to the TDQ as see fit. Thank you!

**Comment by mariearaneta** [comment]
## Update

Just about done with the first 10 agency drafts and added them as a comment nested in the Hubspot task for @laneymangan and @o-ram to review. 

#### Tomorrow (5/24) I will complete and add the following agency drafts - 

City of San Clemente
City of West Hollywood
City of San Juan Capistrano

**Comment by ninadinh-la** [comment]
I completed drafts for my first 10 agencies. Once they send next week, I can task ~10 more to draft and send off accordingly. I suspect these will get quicker as I gain more confidence in emailing agencies myself w/o drafting and review from Laney and Olivia.

**Comment by ninadinh-la** [comment]
I have 4 more emails to hit for my wave 2, they're on hold until I figure out the best communication with Karen. I created hubspot tasks for Wave 3 emails.

**Comment by AnthonyRollins** [comment]
@ninadinh-la @mariearaneta If I remember correctly, we have send out all intro emails. So, I think we can close out this issue.
