### ISSUE TITLE
[New User Request]: Meghan Canale

### ISSUE THREAD

**Issue by ohmegasquared** [cal-itp/customer-success#484]
### Email address

meghan@compiler.la

### Full name

Meghan Canale

### What do you I want to do in Hubspot

- [ ] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [X] Access a Deals pipeline _(payments, data assessments, etc.)_
- [ ] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

Not sure

**Comment by AnthonyRollins** [comment]
Invite sent. @ohmegasquared Let me know if you want training or need help finding something.
