### ISSUE TITLE
[New User Request]: 

### ISSUE THREAD

**Issue by caitlinharper** [cal-itp/customer-success#486]
### Email address

hello@commcoterie.com

### Full name

Caitlin Harper

### What do you I want to do in Hubspot

- [X] Email contacts at transit agencies
- [X] Batch email contacts from multiple agencies
- [X] Access a Deals pipeline _(payments, data assessments, etc.)_
- [X] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

No

**Comment by AnthonyRollins** [comment]
Invite sent
