### ISSUE TITLE
Create sign up form for Benefits monthly updates

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#504]
Right now, the CS team must manually add people to the monthly updates distro list within Hubspot. We would like to allow users to have a self-serve option where they can sign themselves up and automatically be added to the list.

This will ideally be a standalone page, but that is to be confirmed.

**Comment by o-ram** [comment]
@AnthonyRollins, per @indexing 

We likely need both an embedded form and a standalone the form. The standalone form is first priority though, as we can link to it from anywhere—including the Benefits Monthly Update. Ideally, we can later add an embedded form to the Update so people can directly add their email to the list without leaving the page.

**Comment by AnthonyRollins** [comment]
@indexing, what kind of fields would you like? Does First name, Last name, and email work, or would you want only email?

**Comment by indexing** [comment]
Ah yes, of course. Specs! Right now I provide this info for Olivia to add a recipient:

- First name
- Last name
- Email address
- Company

If we have the first three fields here, so that typically give us enough info to associate it with existing profiles in Hubspot? Maybe make the first three field required and the "company" optional?

**Comment by AnthonyRollins** [comment]
We only need the email address associated with contacts in Hubspot. So, I will take a first pass and add it here soon.

**Comment by AnthonyRollins** [comment]
@indexing Here's the draft form: https://app.hubspot.com/forms/5519226/editor/b82f5668-5453-4093-a065-7120a6566b45/edit/form?redirectUrl=/forms/5519226

**Comment by indexing** [comment]
@AnthonyRollins This will work! Thanks. A couple questions:

1. Do I have access to modify the styling and add the intro content? Might be easiest way to iterate on look and feel.
2. Sounds like we don’t need any info besides email address. After trying the form, I’m leaning toward having only this single field to make sign-up as frictionless as possible. Have you used this form approach for other email sign-ups? Curious to hear your thoughts on what to ask for.

**Comment by AnthonyRollins** [comment]
Response and follow-up can be found here: https://compilerla.slack.com/archives/C072WT25BEU/p1721261205546929

**Comment by AnthonyRollins** [comment]
@indexing I believe we can close this out, but let me know if there are any other changes you might need
