### ISSUE TITLE
Research ways to view past emails from Hubspot externally

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#505]
_Does Hubspot provide a summary list of all emails sent as part of a particular “campaign?” In other words, is there a link we can provide that shows a list of all the previous Benefits Monthly Updates within Hubspot?_

**Comment by AnthonyRollins** [comment]
We will have to create a web page and manually add links to each monthly email. 

Current working draft: https://app.hubspot.com/website/5519226/pages/landing/all

**Comment by AnthonyRollins** [comment]
@indexing Are you planning to use the Benefits Doc page for this, or do you still want to keep things in Hubspot? If you planning on using Github, I can close out this issue. Happy to send you the archive email links that you can use.

**Comment by AnthonyRollins** [comment]
@indexing Was a decision made about this?

**Comment by indexing** [comment]
@AnthonyRollins Yes. We will use a Benefits Doc page to share of summary of the monthly updates. Thanks for the follow-up!
