### ISSUE TITLE
Add closed loop payment information to Hubspot profiles

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#510]
For all agencies in the tier list, [the spreadsheet](https://docs.google.com/spreadsheets/d/1qWzuW07Tbq05ww6p9iMGPUZ5d4eqkbwS/edit?gid=2018946141#gid=2018946141) now contains information on those who accept one of the major closed loop cards in the state. This information should be present on the agency's company profile in Hubspot. A custom property is likely needed for this.

**Comment by AnthonyRollins** [comment]
All information has been added to Hubspot
