### ISSUE TITLE
Add Calli from Rebel please

### ISSUE THREAD

**Issue by AngellyTovar** [cal-itp/customer-success#512]
### Email address

calli.cenizal@rebelgroup.com

### Full name

Calli Cenizal

### What do you I want to do in Hubspot

- [X] Email contacts at transit agencies
- [ ] Batch email contacts from multiple agencies
- [X] Access a Deals pipeline _(payments, data assessments, etc.)_
- [X] Respond to support tickets
- [ ] Not sure

### Do you need training on how to use Hubspot?

Yes

**Comment by AnthonyRollins** [comment]
@AngellyTovar Invite sent to Calli
