### ISSUE TITLE
Upload Benefits Webinar to Cal-ITP Youtube channel

### ISSUE THREAD

**Issue by mariearaneta** [cal-itp/customer-success#518]
### To do in YT Studio

- [x] Upload video 
- [x] Add chapters
- [x] Add poster

**Reference**

[Customer Success shared drive, in the Webinar folder](https://drive.google.com/drive/u/1/folders/1-EDQHXx3_e6Vgai2qPNScpZjTOBCDtW6)

**Aiming to be completed by EOD August 2, 2024**

**Comment by mariearaneta** [comment]
@indexing This is uploaded with chapters and poster. Could you check it and give me any notes if necessary before publishing?

**Comment by indexing** [comment]
@mariearaneta Looks great! Exactly what I had in mind—thanks for putting the chapters and times in the description as well. I added the date of the recording at the end. Feel free to move it elsewhere if you see fit. We're ready to publish!

**Comment by mariearaneta** [comment]
@indexing Putting the times in the description is how you add chapters manually. There's also an option for automatic chapters. Thanks for adding the recording date. It is now public on Youtube. 

https://www.youtube.com/watch?v=t5lQY0pBE-k
