### ISSUE TITLE
Import APTA Tech attendee and speaker data

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#525]
Import all data from APTA tech
- [x] Add all speaker details to [Hubspot notes](https://s6.goeshow.com/apta/tech/2024/fullprogram.cfm)
- [x] Add all [attendee data](https://docs.google.com/spreadsheets/d/1EnpWS_NKp7t6Tdd7dFcMhMadbpPgEyWk7sWj3QNqjwY/edit?gid=0#gid=0)

**Comment by AnthonyRollins** [comment]
@adamglinder-la I saw that you imported the attendee data into the CRM, did you by any chance, break out the vendors and import them as the new custom object for vendors?

**Comment by adamglinder-la** [comment]
@AnthonyRollins Gah! Thanks for the reminder. That was on my to-do, but alas I had not yet.

**Comment by adamglinder-la** [comment]
@AnthonyRollins confirming that "add all speaker details to HubSpot notes," you mean manually write in which Program they spoke at on each Contact's page?

**Comment by AnthonyRollins** [comment]
@adamglinder-la We can import those notes, too, if it is all in a spreadsheet. We don't usually do all speakers, just the ones of agencies and vendors we work with the most.

**Comment by laneymangan** [comment]
Here's a list of our agencies that took part in sessions: 

Nina agencies
Buying Cheaper Buses: Use of Joint & Group Procurements
Panelist: Erin Rogers, **Omnitrans**

Taking Stock of the ZEB Transition
Panelist: **Sunline**, Mona Babauto

Mobilizing Millions: Optimizing Transit for Mega Events
Moderator: Stephanie Wiggins, Chief Executive Office, **Los Angeles County Metropolitan Transportation Authority**

School’s In Session: How LA Metro Builds Tomorrow’s Transportation Leaders
Panelist: Dawn Jackson-Perkins, Interim Chief People Officer, **Los Angeles County Metropolitan Transportation Authority**

Multimodal Corridors: Holistic Approaches to Regional Mobility
Panelist: Michael Cano, Executive Officer – Countywide Planning & Development, **Los Angeles County Metropolitan Transportation Authority**

The Rapid Ascent of Customer Experience Programs
Panelist: Jennifer Vides, Chief Customer Experience Officer, **Los Angeles County Metropolitan Transportation Authority**

Marie agencies
Transforming Mobility: Strategic Transportation Initiatives Shaping Southern California’s Future
Panelist: Darrell Johnson, Chief Executive Officer, **Orange County Transportation Authority (OCTA)**

Workforce Revolution: New Models, Practices and Partnerships
Panelist: Shelly Valenton, Deputy General Manager/CEO, **SacRT**

Innovations in Transit and Rail Safety
Panelist: Lisa Hinz, Vice President of Safety, Security and Customer Satisfaction, **SacRT**

**Comment by adamglinder-la** [comment]
Thanks to Laney for the info above, I have added all the info into the HubSpot contacts and this issue is closed.
