### ISSUE TITLE
[Outreach Campaign Request]: GTFS-RT Latency and GTFS-RT Cancellations 

### ISSUE THREAD

**Issue by vevetron** [cal-itp/customer-success#527]
### Subject Matter of Campaign

GTFS-RT Latency and GTFS-RT Cancellations

### Which teams are involved in this campaign

Transit Data Quality

### Does this campaign have a specific deadline and/or timeline associated with it?

None

### What is the reason for conducting this campaign?

I'm reaching out today because at Caltrans we're doing some research into the realtime data quality of GTFS-RT. Specifically, we're analyzing vehicle position latency and trip cancellation information. This information will help inform us of how agencies operate, what kind of data quality we are able to expect given existing technology, and potentially inform future protocols and research. This is strictly for academic research.

### What is the goal of this campaign?

Get agencies and some vendors to answer a number of questions for academic research.

### Who does this campaign target?

- Transit agencies with GTFS-RT systems that cancel and don't cancel trips
- Transit agencies with with latency issues

### Does your campaign request to hold interviews with the customers?

Yes

### Do you envision needing a pipeline for this campaign?

No

**Comment by adamglinder-la** [comment]
Throwing the [AirTable Progress](https://airtable.com/app5FJDUn9iBfjfjB/tblLCLoSHi6xZLnN0/viwKZkv4B65qpPjrs?blocks=hide) link in here for easy access. 

FYI, Scott and I had met with Vivek, Saiful, and Evan on this in July about Vendor research. We put a pin in the outreach early August while we reached out to prioritize the RFP, but are picking it back up now. 

Laney informed me that she had discussions with the team throughout July that they were now including Agencies, so now it's an all hands on deck outreach. ...and that's what you missed! Go Team!

**Comment by adamglinder-la** [comment]
Initial Outreach for Vendor contact emails went out 8/22/24

Evan, Vivek, Saiful, Farhad, and Scott are CC'd in order to help organize meeting times once we get to that point.

**Comment by adamglinder-la** [comment]
After completing minimum five interviews each, the TDQ team confirmed the interviews needed to be done for this research campaign has been completed. Adam confirmed with Saiful on 10/15/24.
