### ISSUE TITLE
Update the Remix pipeline

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#533]
For the remix campaign, we intend to use the existing SchaaS pipeline, but modify it for this next phase of the product scheduler work.

Steps roughly include:

- [x] rename pipeline
- [x] rename stages
- [x] Set up workflow so that a deal is created upon form submission

More steps to be added as we determine everything that needs to be done to update this pipeline.

**Comment by AnthonyRollins** [comment]
@o-ram Workflow automation is setup with the form.

**Comment by AnthonyRollins** [comment]
I moved this to a `low` priority as we await the next steps.
