### ISSUE TITLE
Transition agencies

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#534]
Laney and Olivia are scaling back AM work to scale up program development work. To do so, we need to transition some agencies to Nina and Marie. This issue will track high level progress with this transition

- [x] Develop list of agencies
- [x] Develop transition plan (week of 8/19)
- [x] Transition the agencies (week of 8/26 +) (All participating in this, the spreadsheet contains notes on the transition plan)
- [x] Ensure Hubspot records and spreadsheet are updated (week of 8/26 +) (@ninadinh-la @mariearaneta will update the AM field in Hubspot for their newly assigned agencies; Olivia will take care of the spreadsheet)

**Comment by o-ram** [comment]
List has been developed and a rough sketch of the plan has been discussed. 

Week of 8/19: @ninadinh-la and @mariearaneta to review the list and provide any comments or questions.
Week of 8/26: Outreach to agencies about transition begins

**Comment by o-ram** [comment]
Great! Let's save SolTrans (Solano county) because that's a loaded history that I should explain to you before we do anything.

**Comment by ninadinh-la** [comment]
I reviewed the newly assigned agencies in the document.  I noted suggested plans for their transition based on the communication I saw on hubspot.

**Comment by o-ram** [comment]
@ninadinh-la @mariearaneta I added you both as assignees for this issue since the last 2 steps are a little on all of us, depending on the agency in question.

**Comment by laneymangan** [comment]
Hi @mariearaneta and @ninadinh-la! Can you take a few minutes to update column AB in our [agency transition tab](https://docs.google.com/spreadsheets/d/1qWzuW07Tbq05ww6p9iMGPUZ5d4eqkbwS/edit?gid=773027444#gid=773027444)? Feel free to tag @o-ram or myself in comments in the SS if there are any questions on specific agencies. Let me know here once you're done and then we can determine if we can close out this ticket. Thanks!!

**Comment by laneymangan** [comment]
As of 11/4/24, column AB is up to date. We're keeping this issue open until all remaining 7 agencies have been officially transitioned.
