### ISSUE TITLE
Research the number of conversations held with google maps in the CRM

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#535]
One of the most valued Cal-ITP services offered is assistance with getting feeds in trip planners. There have consistently been blockers with Google in this work. It would help the TDQ team to know the amount of conversations that have taken place with Google.

Question: Can CS count the number of conversations we have had with google maps for each transit agency utilizing the crm?

This issue initially serves as a place to brainstorm and determine how we might go about doing this.

**Comment by o-ram** [comment]
We could categorize these conversations in the inbox or track them as tickets (either multiple or one big one that tracks activity). Could make a Google support pipeline. Ultimately need something to filter on.

**Comment by evansiroky** [comment]
@o-ram at this point, I'm just looking to get a total count by agency of the number of emails (inbound or outbound) we've had with Google Maps regarding trip planner assistance. This is a one-time data request that will then be put into a problem statement document that we'll send to Google and potentially others.

**Comment by o-ram** [comment]
[Google maps data](https://app.hubspot.com/advanced-builder/5519226/report/119778484) research found here in Hubspot.
