### ISSUE TITLE
Customer Success Newsletter #3

### ISSUE THREAD

**Issue by ProvvidenzaC** [cal-itp/customer-success#544]
Updating the content format of the Fall Newsletter for September 17-19 release date 

- [x] Work session with @o-ram and @laneymangan 
- [x] @ProvvidenzaC writes first draft 
- [x] @o-ram and @laneymangan review 
- [x] @ProvvidenzaC send
- [ ] Formalize content flow for future newsletters

**Comment by ProvvidenzaC** [comment]
Updated to reflect new due date.

**Comment by AnthonyRollins** [comment]
@ProvvidenzaC can we close this out?
