### ISSUE TITLE
[Outreach Campaign Request]: Transit Data Guidelines v4

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/customer-success#545]
### Subject Matter of Campaign

Outreach for Transit Data Guidelines v4

### Which teams are involved in this campaign

Transit Data Quality

### Does this campaign have a specific deadline and/or timeline associated with it?

None

### What is the reason for conducting this campaign?

Transit Data Quality is updating the Transit Data Guidelines to version 4. We'd like to reach out to vendors for review of the guidelines and then once feedback has been incorporated, we'd like to do a public outreach campaign informing various people about the updates.

### What is the goal of this campaign?

To increase awareness of what Cal-ITP is expecting for with data quality and to keep entities informed that we continue to update the guidelines.

### Who does this campaign target?

All transit agencies, vendors.

### Does your campaign request to hold interviews with the customers?

No

### Do you envision needing a pipeline for this campaign?

No

**Comment by adamglinder-la** [comment]
[Campaign Guide ](https://docs.google.com/document/d/1IwcqGIsdrJI_Uf1RGgba7sqalGUpbW5J6Pw6JjkCI_I/edit#heading=h.m6ej4z561ovz)is linked here.

Initial emails have been sent to prospective Vendors, will follow up with second emails by EOW for those unresponsive.

**Comment by adamglinder-la** [comment]
confirmed with Evan and TDQ team that this campaign is now closed. 

Per Laney,
> AMs will wrap up any table edits in the campaign guide but will not conduct any further outreach. If we receive any delayed feedback, we'll send it over to the TDQ team.
