### ISSUE TITLE
Update github Campaign Request Form

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/customer-success#554]
"does your campaign have a timeline" is a drop-down, yes/no. We should add a follow-up mandatory question "if yes, what is the timeline/deadline?"

**Comment by AnthonyRollins** [comment]
@laneymangan @o-ram is there any other questions we want to add?

**Comment by o-ram** [comment]
@AnthonyRollins  Not that we know of right now, but we might come up with further edits once the campaign guide template is finished...up to you if you want to push this change now or hold off in case we soon have additional things to add.

**Comment by AnthonyRollins** [comment]
@o-ram PR ready for review #570
