### ISSUE TITLE
[Reporting Request]: Quarterly Report Q3 

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#562]
### What kind of data are you looking for?

Content draft: https://docs.google.com/document/d/1OK97cFXSEnjoON6mfJDVnMsGiO7VhYUpp3SuyQngcdQ/edit
Figma file: https://www.figma.com/files/1365715612369362268/project/49641184/Cal-ITP-Reports?fuid=1235272345470870541

With the success of the Q2 report, we plan on sending the next one around October 15th

Dashboards

- Metabase report: https://metabase.k8s.calitp.jarv.us/dashboard/226-customer-success-quarterly-reporting
- Hubspot report: https://app.hubspot.com/reports-dashboard/5519226/view/13151714

### When would you like to receive this report?

Quarterly

**Comment by AnthonyRollins** [comment]
@srhhnry We are planning to have this for you by early next week. Let me know if you have any questions.

**Comment by srhhnry** [comment]
Hi @AnthonyRollins---no problem. I do need a bit more context here. Are you looking for a creation of a new report using that Figma template and some new content? If so, do you have a previous, designed, version of the report handy so I can take a look at a final product? And what is the deadline for completion? 

thanks!

**Comment by AnthonyRollins** [comment]
@srhhnry We need to input new content and images into the[ template](https://www.figma.com/files/1365715612369362268/project/49641184/Cal-ITP-Reports?fuid=1235272345470870541). Here is a [link to the last report](https://drive.google.com/file/d/13FhmQMgef4ChkRSYcMGvT-9f3MXzn0EL/view?usp=drive_link) to see how it looks. 

We hope to have it into the new template by October 15th.

**Comment by o-ram** [comment]
Since the Q3 report has been finalized and sent out, I am closing this issue.
