### ISSUE TITLE
Contact list requests for Caltrans

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#585]
1. Need to send a call for awards for the Excellence in Transportation (EIT) Awards to stakeholders. Maya has been asked for an email stakeholder list or excel list of cities, counties, RTPA and MPO’s that she can share. 
2. List of rural transit providers (5311) that could support rural tribes for AHSC projects. Do you happen to have an extensive list of 5311 providers or Tribal transit providers?
3. I am looking for more third-party on-demand providers – Via keeps coming to mind.

This issue will be completed when the following are delivered to Maya:
- [x] export all “Transit Agencies” and “Government Agencies”
- [x] export list of 5311 providers or Tribal transit providers
- [x] Share list of third part on-demand providers (i.e. Via)

**Comment by adamglinder-la** [comment]
FYI, I sent Maya the current on demand vendor contact list on 12/10/24. Will update here if more is needed. :)

**Comment by o-ram** [comment]
All 3 lists have been delivered to Maya. Issue is marked as "in review" while I wait to hear if we have provided her with everything she needs.

**Comment by o-ram** [comment]
I shared an updated 5311 list with Maya on 12/11 that filters by agencies in tiers B-D _and_ contacts within those agencies that have logged activity in 2024. Awaiting to hear if this is more in-line with what she needs.

**Comment by o-ram** [comment]
The new 5311 list works well! As all lists have been delivered and there is no further outstanding feedback, this issue will be closed.
